import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  static const Map<String, String> supportedLocales = {
    'en': 'English',
    'hi': 'हिन्दी (Hindi)',
    'as': 'অসমীয়া (Assamese)',
    'bn': 'বাংলা (Bengali)',
    'brx': 'बरो (Bodo)',
    'doi': 'डोगरी (Dogri)',
    'gu': 'ગુજરાતી (Gujarati)',
    'kn': 'ಕನ್ನಡ (Kannada)',
    'ks': 'کٲشূর (Kashmiri)',
    'kok': 'कोंकणी (Konkani)',
    'mai': 'मैथिली (Maithili)',
    'ml': 'മലയാളം (Malayalam)',
    'mni': 'মৈতৈলোন (Manipuri)',
    'mr': 'मराठी (Marathi)',
    'ne': 'नेपाली (Nepali)',
    'or': 'ଓଡ଼ିଆ (Odia)',
    'pa': 'ਪੰਜਾਬੀ (Punjabi)',
    'sa': 'संस्कृतम् (Sanskrit)',
    'sat': 'ᱥᱟᱱᱛᱟᱲᱤ (Santali)',
    'sd': 'سنڌي (Sindhi)',
    'ta': 'தமிழ் (Tamil)',
    'te': 'తెలుగు (Telugu)',
    'ur': 'اردو (Urdu)',
  };

  String _currentLocale = 'en';

  String get currentLocale => _currentLocale;

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLocale = prefs.getString('app_language_locale') ?? 'en';
    notifyListeners();
  }

  Future<void> setLanguage(String locale) async {
    if (locale == _currentLocale) return;
    _currentLocale = locale;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('app_language_locale', locale);
    notifyListeners();
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'GigTax',
      'nav_home': 'Home',
      'nav_analytics': 'Analytics',
      'nav_receipts': 'Receipts',
      'nav_tax': 'Tax',
      'nav_settings': 'Settings',
      'settings_title': 'Settings Center',
      'settings_account_info': 'Account Info',
      'settings_member': 'Verified Member',
      'settings_system_toggles': 'System & Toggles',
      'settings_sms_title': 'Automatic SMS Parsing',
      'settings_sms_sub': 'Process financial receipt SMS in the background',
      'settings_imports_title': 'Automatic Statement Imports',
      'settings_imports_sub': 'Allow CSV & text statement conversions',
      'settings_notif_title': 'Save Notification History',
      'settings_notif_sub': 'Store in-app notifications in local history',
      'settings_biometric_title': 'Biometric Lock Screen',
      'settings_biometric_sub': 'Prompt for fingerprint/FaceID on app startup',
      'settings_monetization': 'Monetization & Startup Growth',
      'settings_upgrade': 'Upgrade to GigTax Pro',
      'settings_upgrade_sub': 'Access What-If simulator, local AI tax advisor, and unlimited PDF exports',
      'settings_founder': 'Founder Command Center',
      'settings_founder_sub': 'Real-time startup health, user retention cohorts, support tickets, and performance indicators',
      'settings_support': 'Submit Support Ticket & Feedback',
      'settings_support_sub': 'Rate experience, submit bug reports, feature requests, or contact support',
      'settings_referral': 'Referral Program & Rewards',
      'settings_referral_sub': 'Share your referral code and earn ₹500 in Pro credits',
      'settings_storage': 'Storage & Management',
      'settings_clear_logs': 'Clear Transaction Logs',
      'settings_clear_logs_sub': 'Wipe out all local and cached transactional records',
      'settings_import_mock': 'Import Test Data',
      'settings_import_mock_sub': 'Add 6+ mock transaction receipts for dashboard testing',
      'tax_report_center': 'Tax Report Center (CA-Ready)',
      'tax_report_sub': 'Download dedicated PDF logs matching your business requirements.',
      'tax_generate_btn': 'Generate and Download Report',
    },
    'hi': {
      'app_title': 'गिगटैक्स (GigTax)',
      'nav_home': 'होम',
      'nav_analytics': 'एनालिटिक्स',
      'nav_receipts': 'रसीदें',
      'nav_tax': 'टैक्स',
      'nav_settings': 'सेटिंग्स',
      'settings_title': 'सेटिंग्स केंद्र',
      'settings_account_info': 'खाता जानकारी',
      'settings_member': 'सत्यापित सदस्य',
      'settings_system_toggles': 'सिस्टम और टॉगल',
      'settings_sms_title': 'स्वचालित एसएमएस पार्सिंग',
      'settings_sms_sub': 'बैकग्राउंड में वित्तीय रसीद एसएमएस प्रोसेस करें',
      'settings_imports_title': 'स्वचालित स्टेटमेंट इंपोर्ट',
      'settings_imports_sub': 'CSV और टेक्स्ट स्टेटमेंट कन्वर्शन सक्षम करें',
      'settings_notif_title': 'नोटिफिकेशन हिस्ट्री सहेजें',
      'settings_notif_sub': 'इन-ऐप नोटिफिकेशन को लोकल स्टोरेज में सहेजें',
      'settings_biometric_title': 'बायोमेट्रिक लॉक स्क्रीन',
      'settings_biometric_sub': 'ऐप स्टार्टअप पर फिंगरप्रिंट/FaceID मांगें',
      'settings_monetization': 'मुद्रीकरण और स्टार्टअप विकास',
      'settings_upgrade': 'गिगटैक्स प्रो में अपग्रेड करें',
      'settings_upgrade_sub': 'वॉट-इफ सिम्युलेटर, लोकल एआई टैक्स सलाहकार और अनलिमिटेड PDF एक्सपोर्ट पाएं',
      'settings_founder': 'फाउंडर कमांड सेंटर',
      'settings_founder_sub': 'स्टार्टअप स्वास्थ्य, उपयोगकर्ता प्रतिधारण समूह, समर्थन टिकट और प्रदर्शन संकेतक',
      'settings_support': 'सपोर्ट टिकट और फीडबैक भेजें',
      'settings_support_sub': 'अनुभव को रेट करें, बग रिपोर्ट, फीचर अनुरोध सबमिट करें',
      'settings_referral': 'रेफरल कार्यक्रम और पुरस्कार',
      'settings_referral_sub': 'अपना रेफरल कोड साझा करें और ₹500 प्रो क्रेडिट अर्जित करें',
      'settings_storage': 'स्टोरेज और प्रबंधन',
      'settings_clear_logs': 'लेनदेन लॉग्स साफ करें',
      'settings_clear_logs_sub': 'सभी स्थानीय और कैश्ड लेनदेन रिकॉर्ड हटा दें',
      'settings_import_mock': 'टेस्ट डेटा इंपोर्ट करें',
      'settings_import_mock_sub': 'डैशबोर्ड टेस्टिंग के लिए 6+ मॉक रसीदें जोड़ें',
      'tax_report_center': 'टैक्स रिपोर्ट केंद्र (CA-Ready)',
      'tax_report_sub': 'अपनी व्यावसायिक आवश्यकताओं के अनुसार समर्पित PDF लॉग डाउनलोड करें।',
      'tax_generate_btn': 'रिपोर्ट बनाएं और डाउनलोड करें',
    },
    'as': {
      'app_title': 'গিগট্যাক্স (GigTax)',
      'nav_home': 'ঘৰ',
      'nav_analytics': 'বিশ্লেষণ',
      'nav_receipts': 'ৰচিদসমূহ',
      'nav_tax': 'কৰ',
      'nav_settings': 'ছেটিংছ',
      'settings_title': 'ছেটিংছ কেন্দ্ৰ',
      'settings_account_info': 'অ্যাকাউন্ট তথ্য',
      'settings_member': 'যাচাই কৰা সদস্য',
      'settings_system_toggles': 'ছিষ্টেম টগলসমূহ',
      'settings_sms_title': 'স্বয়ংক্ৰিয় এছএমএছ বিশ্লেষণ',
      'settings_sms_sub': 'পৃষ্ঠভূমিত বিত্তীয় ৰচিদৰ এছএমএছ প্ৰক্ৰিয়াকৰণ কৰক',
      'settings_imports_title': 'স্বয়ংক্ৰিয় বিবৃতি আমদানি',
      'settings_imports_sub': 'CSV আৰু পাঠ্য বিবৃতি ৰূপান্তৰৰ অনুমতি দিয়ক',
      'settings_notif_title': 'জাননী ইতিহাস সংৰক্ষণ কৰক',
      'settings_notif_sub': 'ইন-এপ জাননীসমূহ স্থানীয় ইতিহাসত সংৰক্ষণ কৰক',
      'settings_biometric_title': 'বায়োমেট্ৰিক লক স্ক্ৰীণ',
      'settings_biometric_sub': 'এপ আৰম্ভণিতে আঙুলিৰ ছাপ/ফেচ আই ডি বিচাৰক',
      'settings_monetization': 'মুদ্ৰাকৰণ আৰু ষ্টাৰ্টআপ বৃদ্ধি',
      'settings_upgrade': 'গিগট্যাক্স প্ৰোলৈ উন্নীত কৰক',
      'settings_upgrade_sub': 'হোৱাট-ইফ চিমুলেটৰ, স্থানীয় এআই কৰ পৰামৰ্শদাতা, আৰু সীমাহীন পিডিএফ ৰিপোৰ্ট লাভ কৰক',
      'settings_founder': 'প্ৰতিষ্ঠাপক কমাণ্ড কেন্দ্ৰ',
      'settings_founder_sub': 'ষ্টাৰ্টআপৰ স্বাস্থ্য, ব্যৱহাৰকাৰীৰ ধৰি ৰখা কোহোৰ্ট, আৰু সমৰ্থন টিকটসমূহ',
      'settings_support': 'সমৰ্থন টিকট আৰু মতামত প্ৰেৰণ কৰক',
      'settings_support_sub': 'অভিজ্ঞতা মূল্যাংকন কৰক, বা সমৰ্থনৰ সৈতে যোগাযোগ কৰক',
      'settings_referral': 'ৰেফাৰেল কাৰ্যসূচী আৰু পুৰস্কাৰ',
      'settings_referral_sub': 'আপোনাৰ ৰেফাৰেল ক’ড শ্বেয়াৰ কৰক আৰু ₹৫০০ লাভ কৰক',
      'settings_storage': 'সংৰক্ষণ আৰু ব্যৱস্থাপনা',
      'settings_clear_logs': 'লেনদেন লগসমূহ মচি পেলাওক',
      'settings_clear_logs_sub': 'সকলো স্থানীয় লেনদেনৰ ৰেকৰ্ড মচি পেলাওক',
      'settings_import_mock': 'পৰীক্ষামূলক তথ্য আমদানি কৰক',
      'settings_import_mock_sub': 'ড্যাশবৰ্ড পৰীক্ষাৰ বাবে ৬+ মক ৰচিদ যোগ কৰক',
      'tax_report_center': 'কৰ ৰিপোৰ্ট কেন্দ্ৰ (CA-Ready)',
      'tax_report_sub': 'আপোনাৰ ব্যৱসায়িক প্ৰয়োজনীয়তাৰ সৈতে খাপ খোৱা পিডিএফ সংৰক্ষণ কৰক।',
      'tax_generate_btn': 'ৰিপোৰ্ট প্ৰস্তুত আৰু ডাউনলোড কৰক',
    },
    'bn': {
      'app_title': 'গিগট্যাক্স (GigTax)',
      'nav_home': 'হোম',
      'nav_analytics': 'বিশ্লেষণ',
      'nav_receipts': 'রসিদসমূহ',
      'nav_tax': 'কর',
      'nav_settings': 'সেটিংস',
      'settings_title': 'সেটিংস সেন্টার',
      'settings_account_info': 'অ্যাকাউন্টের তথ্য',
      'settings_member': 'যাচাইকৃত সদস্য',
      'settings_system_toggles': 'সিস্টেম ও টগল',
      'settings_sms_title': 'স্বয়ংক্রিয় এসএমএস পার্সিং',
      'settings_sms_sub': 'ব্যাকগ্রাউন্ডে আর্থিক রসিদ এসএমএস প্রসেস করুন',
      'settings_imports_title': 'স্বয়ংক্রিয় স্টেটমেন্ট ইম্পোর্ট',
      'settings_imports_sub': 'CSV ও টেক্সট স্টেটমেন্ট রূপান্তর সক্ষম করুন',
      'settings_notif_title': 'নোটিফিকেশন ইতিহাস সংরক্ষণ করুন',
      'settings_notif_sub': 'ইন-অ্যাপ নোটিফিকেশন স্থানীয় ইতিহাসে সংরক্ষণ করুন',
      'settings_biometric_title': 'বায়োমেট্রিক লক স্ক্রিন',
      'settings_biometric_sub': 'অ্যাপ চালুর সময় ফিঙ্গারপ্রিন্ট/ফেস আইডি প্রম্পট করুন',
      'settings_monetization': 'মনিটাইজেশন ও স্টার্টআপ বৃদ্ধি',
      'settings_upgrade': 'গিগট্যাক্স প্রো-তে আপগ্রেড করুন',
      'settings_upgrade_sub': 'হোয়াট-ইফ সিমুলেটর, স্থানীয় এআই ট্যাক্স উপদেষ্টা এবং আনলিমিটেড পিডিএফ পান',
      'settings_founder': 'প্রতিষ্ঠাতা কমান্ড সেন্টার',
      'settings_founder_sub': 'স্টার্টআপের স্বাস্থ্য, ব্যবহারকারী ধারণ কোহর্ট এবং সমর্থন টিকিট',
      'settings_support': 'সহায়তা টিকিট ও মতামত পাঠান',
      'settings_support_sub': 'অভিজ্ঞতা রেট করুন বা সহায়তার সাথে যোগাযোগ করুন',
      'settings_referral': 'রেফারেল প্রোগ্রাম ও পুরস্কার',
      'settings_referral_sub': 'আপনার রেফারেল কোড শেয়ার করুন এবং ₹৫০০ প্রফিট ক্রেডিট পান',
      'settings_storage': 'স্টোরেজ ও ম্যানেজমেন্ট',
      'settings_clear_logs': 'লেনদেনের লগ মুছে ফেলুন',
      'settings_clear_logs_sub': 'সব স্থানীয় এবং ক্যাশ লেনদেন রেকর্ড মুছে ফেলুন',
      'settings_import_mock': 'পরীক্ষামূলক ডেটা ইম্পোর্ট করুন',
      'settings_import_mock_sub': 'ড্যাশবোর্ড পরীক্ষার জন্য ৬+ মক রসিদ যোগ করুন',
      'tax_report_center': 'কর রিপোর্ট কেন্দ্র (CA-Ready)',
      'tax_report_sub': 'আপনার ব্যবসায়িক প্রয়োজন অনুযায়ী পিডিএফ ডাউনলোড করুন।',
      'tax_generate_btn': 'রিপোর্ট তৈরি ও ডাউনলোড করুন',
    },
    'brx': {
      'app_title': 'गिगटैक्स (GigTax)',
      'nav_home': 'नोगो',
      'nav_analytics': 'बिजिरनाय',
      'nav_receipts': 'रसिदफोर',
      'nav_tax': 'टैक्स',
      'nav_settings': 'सेटिंगफोर',
      'settings_title': 'सेटिंग सेंटर',
      'settings_account_info': 'खाता मिथिसारनाय',
      'settings_member': 'गोनायथि जानाय सोद्रोमा',
      'settings_system_toggles': 'सिस्टम आरो टगलफोर',
      'settings_sms_title': 'गावनोगावनो एसएमएस पार्सिंग',
      'settings_sms_sub': 'बैकग्राउंडआव रांआरि रसिद एसएमएस प्रसेस खालाम',
      'settings_imports_title': 'गावनोगावनो स्टेटमेन्ट इम्पोर्ट',
      'settings_imports_sub': 'CSV आरो टेक्स्ट स्टेटमेन्ट सोलायनायखौ गनायथि हो',
      'settings_notif_title': 'फोरमायनाय जारिमिन लाखि',
      'settings_notif_sub': 'इन-एप फोरमायनायफोरखौ जायगायाव लाखि',
      'settings_biometric_title': 'बायोमेट्रिक लक स्क्रिन',
      'settings_biometric_sub': 'एप जागायनायाव फिंगरप्रिन्ट/फेस आइडी नागिर',
      'settings_monetization': 'रां खालामनाय आरो जागायनाय बाढायनाय',
      'settings_upgrade': 'गिगटैक्स प्रो आव अपग्रेड खालाम',
      'settings_upgrade_sub': 'वॉट-इफ सिम्युलेटर, जायगायाव एआई टैक्स सुबहागिरि आरो अनलिमिटेड पीडीएफ मोनो',
      'settings_founder': 'गायसलग कमांड सेंटर',
      'settings_founder_sub': 'स्टार्टআপ गोख्रोंथि, बाहायगिरि जारिमिन आरो मदद टिकटफोर',
      'settings_support': 'मदद टिकट आरो फीडबैक हर',
      'settings_support_sub': 'रोंमोननायखौ रेट खालाम, बग रिपोर्ट सबमिट खालाम',
      'settings_referral': 'रेफरल कार्यक्रम आरो बान्थाफोर',
      'settings_referral_sub': 'नोङोनि रेफरल कोडखौ रान आरो ₹५०० प्रो क्रेडिट मोनो',
      'settings_storage': 'स्टोरेज आरो सामलायनाय',
      'settings_clear_logs': 'लेनदेन लोगफोरखौ साखोन-सिखोन खालाम',
      'settings_clear_logs_sub': 'गासैबो जायगायाव थानाय लेनदेन रेकर्डफोरखौ हुगार',
      'settings_import_mock': 'आनजाद डेटा इम्पोर्ट खालाम',
      'settings_import_mock_sub': 'डैशबोर्ड आनजाद खालामनो थाखाय ६+ नंखाय रसिदफोर दाजाब',
      'tax_report_center': 'टैक्स रिपोर्ट सेंटर (CA-Ready)',
      'tax_report_sub': 'नोङोनि फालांगि गोनांथियै पीडीएफ डाउनलोड खालाम।',
      'tax_generate_btn': 'रिपोर्ट दा आरो डाउनलोड खालाम',
    },
    'doi': {
      'app_title': 'गिगटैक्स (GigTax)',
      'nav_home': 'घर',
      'nav_analytics': 'विश्लेषण',
      'nav_receipts': 'रसीदां',
      'nav_tax': 'टैक्स',
      'nav_settings': 'सेटिंग्स',
      'settings_title': 'सेटिंग्स केंद्र',
      'settings_account_info': 'खाता जानकारी',
      'settings_member': 'सत्यापित सदस्य',
      'settings_system_toggles': 'सिस्टम ते टॉगल',
      'settings_sms_title': 'स्वचालित एसएमएस पार्सिंग',
      'settings_sms_sub': 'बैकग्राउंड च वित्तीय रसीद एसएमएस प्रोग्रेस करो',
      'settings_imports_title': 'स्वचालित स्टेटमेंट इंपोर्ट',
      'settings_imports_sub': 'CSV ते टेक्स्ट स्टेटमेंट कन्वर्शन दी मंजूरी देओ',
      'settings_notif_title': 'सूचना इतिहास सँभालो',
      'settings_notif_sub': 'इन-ऐप सूचना गी स्थानीय स्टोरेज च रखो',
      'settings_biometric_title': 'बायोमेट्रिक लॉक स्क्रीन',
      'settings_biometric_sub': 'ऐप शुरू होन पर उंगली दा निशान/फेस आईडी पूछो',
      'settings_monetization': 'मुद्रीकरण ते स्टार्टअप विकास',
      'settings_upgrade': 'गिगटैक्स प्रो च अपग्रेड करो',
      'settings_upgrade_sub': 'वॉट-इफ सिम्युलेटर, लोकल एआई टैक्स सलाहकार ते असीमित पीडीएफ पाओ',
      'settings_founder': 'संस्थापक कमांड सेंटर',
      'settings_founder_sub': 'स्टार्टअप सेहत, उपभोक्ता प्रतिधारण समूह ते सहायता टिकट',
      'settings_support': 'सहायता टिकट ते फीडबैक देओ',
      'settings_support_sub': 'अनुभव गी रेट करो, बग रिपोर्ट सबमिट करो',
      'settings_referral': 'रेफरल कार्यक्रम ते इनाम',
      'settings_referral_sub': 'अपना रेफरल कोड सांझा करो ते ₹५०० प्रो क्रेडिट कमाओ',
      'settings_storage': 'स्टोरेज ते प्रबंधन',
      'settings_clear_logs': 'लेनदेन लॉग साफ करो',
      'settings_clear_logs_sub': 'सारे स्थानीय ते कैश्ड लेनदेन रिकॉर्ड हटाओ',
      'settings_import_mock': 'टेस्ट डेटा इंपोर्ट करो',
      'settings_import_mock_sub': 'डैशबोर्ड टेस्टिंग लेई ६+ मॉक रसीदां जोड़ो',
      'tax_report_center': 'टैक्स रिपोर्ट केंद्र (CA-Ready)',
      'tax_report_sub': 'अपनी व्यापारिक जरूरतें दे अनुसार समर्पित पीडीएफ डाउनलोड करो।',
      'tax_generate_btn': 'रिपोर्ट बनाओ ते डाउनलोड करो',
    },
    'gu': {
      'app_title': 'ગીગટેક્સ (GigTax)',
      'nav_home': 'હોમ',
      'nav_analytics': 'વિશ્લેષણ',
      'nav_receipts': 'રસીદો',
      'nav_tax': 'ટેક્સ',
      'nav_settings': 'સેટિંગ્સ',
      'settings_title': 'સેટિંગ્સ સેન્ટર',
      'settings_account_info': 'ખાતાની માહિતી',
      'settings_member': 'ચકાસાયેલ સભ્ય',
      'settings_system_toggles': 'સિસ્ટમ અને ટૉગલ્સ',
      'settings_sms_title': 'સ્વચાલિત એસએમએસ વિશ્લેષણ',
      'settings_sms_sub': 'બેકગ્રાઉન્ડમાં નાણાકીય રસીદ એસએમએસ પ્રોસેસ કરો',
      'settings_imports_title': 'સ્વચાલિત સ્ટેટમેન્ટ આયાત',
      'settings_imports_sub': 'CSV અને ટેક્સ્ટ સ્ટેટમેન્ટ કન્વર્ઝનની મંજૂરી આપો',
      'settings_notif_title': 'નોટિફિકેશન ઇતિહાસ સાચવો',
      'settings_notif_sub': 'ઇન-એપ નોટિફિકેશન સ્થાનિક ઇતિહાસમાં સંગ્રહિત કરો',
      'settings_biometric_title': 'બાયોમેટ્રિક લોક સ્ક્રીન',
      'settings_biometric_sub': 'એપ શરૂ થાય ત્યારે ફિંગરપ્રિન્ટ/ફેસ આઈડી માટે પૂછો',
      'settings_monetization': 'મોનેટાઇઝેશન અને સ્ટાર્ટઅપ વિકાસ',
      'settings_upgrade': 'ગીગટેક્સ પ્રો પર અપગ્રેડ કરો',
      'settings_upgrade_sub': 'વૉટ-ઇફ સિમ્યુલેટર, સ્થાનિક એઆઈ ટેક્સ સલાહકાર અને અમર્યાદિત પીડીએફ મેળવો',
      'settings_founder': 'સ્થાપક કમાન્ડ સેન્ટર',
      'settings_founder_sub': 'સ્ટાર્ટઅપ સ્વાસ્થ્ય, વપરાશકર્તા રીટેન્શન અને સપોર્ટ ટિકિટ્સ',
      'settings_support': 'સપોર્ટ ટિકિટ અને ફીડબેક મોકલો',
      'settings_support_sub': 'અનુભવ રેટ કરો, બગ રિપોર્ટ સબમિટ કરો અથવા સંપર્ક કરો',
      'settings_referral': 'રેફરલ પ્રોગ્રામ અને પુરસ્કારો',
      'settings_referral_sub': 'તમારો રેફરલ કોડ શેર કરો અને ₹૫૦૦ પ્રો ક્રેડિટ મેળવો',
      'settings_storage': 'સ્ટોરેજ અને મેનેજમેન્ટ',
      'settings_clear_logs': 'વ્યવહાર લોગ્સ સાફ કરો',
      'settings_clear_logs_sub': 'બધા સ્થાનિક અને કેશ્ડ વ્યવહાર રેકોર્ડ્સ ભૂંસી નાખો',
      'settings_import_mock': 'ટેસ્ટ ડેટા આયાત કરો',
      'settings_import_mock_sub': 'ટેસ્ટિંગ માટે ૬+ મોક રસીદો ઉમેરો',
      'tax_report_center': 'ટેક્સ રિપોર્ટ સેન્ટર (CA-Ready)',
      'tax_report_sub': 'તમારા વ્યવસાયની જરૂરિયાતોને અનુરૂપ સમર્પિત પીડીએફ ડાઉનલોડ કરો.',
      'tax_generate_btn': 'રિપોર્ટ બનાવો અને ડાઉનલોડ કરો',
    },
    'kn': {
      'app_title': 'ಗಿಗ್ಟ್ಯಾಕ್ಸ್ (GigTax)',
      'nav_home': 'ಮುಖಪುಟ',
      'nav_analytics': 'ವಿಶ್ಲೇಷಣೆ',
      'nav_receipts': 'ರಸೀದಿಗಳು',
      'nav_tax': 'ತೆರಿಗೆ',
      'nav_settings': 'ಸೆಟ್ಟಿಂಗ್ಸ್',
      'settings_title': 'ಸೆಟ್ಟಿಂಗ್ಸ್ ಕೇಂದ್ರ',
      'settings_account_info': 'ಖಾತೆ ಮಾಹಿತಿ',
      'settings_member': 'ಪರಿಶೀಲಿಸಿದ ಸದಸ್ಯ',
      'settings_system_toggles': 'ಸಿಸ್ಟಮ್ ಮತ್ತು ಟಾಗಲ್‌ಗಳು',
      'settings_sms_title': 'ಸ್ವಯಂಚಾಲಿತ ಎಸ್‌ಎಂಎಸ್ ಪಾರ್ಸಿಂಗ್',
      'settings_sms_sub': 'ಹಿನ್ನೆಲೆಯಲ್ಲಿ ಹಣಕಾಸು ರಸೀದಿ ಎಸ್‌ಎಂಎಸ್‌ಗಳನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಿ',
      'settings_imports_title': 'ಸ್ವಯಂಚಾಲಿತ ಹೇಳಿಕೆ ಆಮದುಗಳು',
      'settings_imports_sub': 'CSV ಮತ್ತು ಪಠ್ಯ ಹೇಳಿಕೆ ಪರಿವರ್ತನೆಗಳನ್ನು ಅನುಮತಿಸಿ',
      'settings_notif_title': 'ಅಧಿಸೂಚನೆ ಇತಿಹಾಸವನ್ನು ಉಳಿಸಿ',
      'settings_notif_sub': 'ಅಪ್ಲಿಕೇಶನ್‌ನಲ್ಲಿನ ಅಧಿಸೂಚನೆಗಳನ್ನು ಸ್ಥಳೀಯ ಇತಿಹಾಸದಲ್ಲಿ ಉಳಿಸಿ',
      'settings_biometric_title': 'ಬಯೋಮೆಟ್ರಿಕ್ ಲಾಕ್ ಸ್ಕ್ರೀನ್',
      'settings_biometric_sub': 'ಅಪ್ಲಿಕೇಶನ್ ಪ್ರಾರಂಭದಲ್ಲಿ ಫಿಂಗರ್‌ಪ್ರಿಂಟ್/ಫೇಸ್ ಐಡಿಗಾಗಿ ಕೇಳಿ',
      'settings_monetization': 'ಮಾನಿಟೈಸೇಶನ್ ಮತ್ತು ಸ್ಟಾರ್ಟ್ಅಪ್ ಬೆಳವಣಿಗೆ',
      'settings_upgrade': 'ಗಿಗ್ಟ್ಯಾಕ್ಸ್ ಪ್ರೊಗೆ ಅಪ್‌ಗ್ರೇಡ್ ಮಾಡಿ',
      'settings_upgrade_sub': 'ವಾಟ್-ಇಫ್ ಸಿಮ್ಯುಲೇಟರ್, ಸ್ಥಳೀಯ ಎಐ ತೆರಿಗೆ ಸಲಹೆಗಾರ ಮತ್ತು ಅನಿಯಮಿತ ಪಿಡಿಎಫ್ ಪಡೆಯಿರಿ',
      'settings_founder': 'ಸ್ಥಾಪಕ ಕಮಾಂಡ್ ಸೆಂಟರ್',
      'settings_founder_sub': 'ಸ್ಟಾರ್ಟ್ಅಪ್ ಆರೋಗ್ಯ, ಬಳಕೆದಾರರ ಧಾರಣ ಮತ್ತು ಬೆಂಬಲ ಟಿಕೆಟ್‌ಗಳು',
      'settings_support': 'ಬೆಂಬಲ ಟಿಕೆಟ್ ಮತ್ತು ಪ್ರತಿಕ್ರಿಯೆ ಸಲ್ಲಿಸಿ',
      'settings_support_sub': 'ಅನುಭವವನ್ನು ರೇಟ್ ಮಾಡಿ, ದೋಷ ವರದಿಗಳನ್ನು ಸಲ್ಲಿಸಿ',
      'settings_referral': 'ರೆಫರಲ್ ಪ್ರೋಗ್ರಾಂ ಮತ್ತು ಬಹುಮಾನಗಳು',
      'settings_referral_sub': 'ನಿಮ್ಮ ರೆಫರಲ್ ಕೋಡ್ ಹಂಚಿಕೊಳ್ಳಿ ಮತ್ತು ₹೫೦೦ ಗಳಿಸಿ',
      'settings_storage': 'ಸಂಗ್ರಹಣೆ ಮತ್ತು ನಿರ್ವಹಣೆ',
      'settings_clear_logs': 'ವಹಿವಾಟು ಲಾಗ್‌ಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ',
      'settings_clear_logs_sub': 'ಎಲ್ಲಾ ಸ್ಥಳೀಯ ಮತ್ತು ಸಂಗ್ರಹಿಸಲಾದ ವಹಿವಾಟು ದಾಖಲೆಗಳನ್ನು ಅಳಿಸಿ',
      'settings_import_mock': 'ಟೆಸ್ಟ್ ಡೇಟಾವನ್ನು ಆಮದು ಮಾಡಿ',
      'settings_import_mock_sub': 'ಟೆಸ್ಟಿಂಗ್‌ಗಾಗಿ ೬+ ಅಣಕು ರಸೀದಿಗಳನ್ನು ಸೇರಿಸಿ',
      'tax_report_center': 'ತೆರಿಗೆ ವರದಿ ಕೇಂದ್ರ (CA-Ready)',
      'tax_report_sub': 'ನಿಮ್ಮ ವ್ಯವಹಾರದ ಅವಶ್ಯಕತೆಗಳಿಗೆ ಅನುಗುಣವಾಗಿ ಪಿಡಿಎಫ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ.',
      'tax_generate_btn': 'ವರದಿಯನ್ನು ರಚಿಸಿ ಮತ್ತು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    },
    'ks': {
      'app_title': 'گگ ٹیکس (GigTax)',
      'nav_home': 'گھر',
      'nav_analytics': 'تجزیہ',
      'nav_receipts': 'رسید',
      'nav_tax': 'ٹیکس',
      'nav_settings': 'ترتیبات',
      'settings_title': 'ترتیبات مرکز',
      'settings_account_info': 'کھاتہ معلومات',
      'settings_member': 'تصدیق شدہ ممبر',
      'settings_system_toggles': 'سستم ترتیبات',
      'settings_sms_title': 'خودکار ایس ایم ایس پارسنگ',
      'settings_sms_sub': 'بیک گراؤنڈ میں مالیاتی رسید ایس ایم ایس پروسیس کریں',
      'settings_imports_title': 'خودکار اسٹیٹمنٹ امپورٹ',
      'settings_imports_sub': 'CSV اور ٹیکسٹ اسٹیٹمنٹ کنورژن کی اجازت دیں',
      'settings_notif_title': 'نوٹیفیکیشن ہسٹری محفوظ کریں',
      'settings_notif_sub': 'ان ایپ نوٹیفیکیشنز کو مقامی ہسٹری میں محفوظ کریں',
      'settings_biometric_title': 'بایومیٹرک لاک اسکرین',
      'settings_biometric_sub': 'ایپ اسٹارٹ اپ پر فنگر پرنٹ/فیس آئی ڈی کا مطالبہ کریں',
      'settings_monetization': 'مونٹائزیشن اور اسٹارٹ اپ ترقی',
      'settings_upgrade': 'گگ ٹیکس پرو میں اپ گریڈ کریں',
      'settings_upgrade_sub': 'واٹ اف سمیلیٹر، مقامی اے آئی ٹیکس مشیر اور لامحدود پی ڈی ایف حاصل کریں',
      'settings_founder': 'مؤسس کمانڈ سینٹر',
      'settings_founder_sub': 'اسٹارٹ اپ صحت، کسٹمر ریٹینشن اور سپورٹ ٹکٹس',
      'settings_support': 'سپورٹ ٹکٹ اور فیڈ بیک جمع کروائیں',
      'settings_support_sub': 'تجربے کی درجہ بندی کریں یا سپورٹ سے رابطہ کریں',
      'settings_referral': 'ریفرل پروگرام اور انعامات',
      'settings_referral_sub': 'اپنا ریفرل کوڈ شیئر کریں اور ₹۵۰۰ پرو کریڈٹ حاصل کریں',
      'settings_storage': 'اسٹوریج اور انتظام',
      'settings_clear_logs': 'ٹرانزیکشن لاگز صاف کریں',
      'settings_clear_logs_sub': 'تمام مقامی اور کیش شدہ ٹرانزیکشن ریکارڈز صاف کریں',
      'settings_import_mock': 'ٹیسٹ ڈیٹا درآمد کریں',
      'settings_import_mock_sub': 'ٹیسٹنگ کے لیے ۶+ فرضی رسیدیں شامل کریں',
      'tax_report_center': 'ٹیکس رپورٹ مرکز (CA-Ready)',
      'tax_report_sub': 'اپنی کاروباری ضروریات کے مطابق پی ڈی ایف ڈاؤن لوڈ کریں۔',
      'tax_generate_btn': 'رپورٹ تیار اور ڈاؤن لوڈ کریں',
    },
    'kok': {
      'app_title': 'गिगटॅक्स (GigTax)',
      'nav_home': 'घर',
      'nav_analytics': 'विश्लेषण',
      'nav_receipts': 'पावती',
      'nav_tax': 'टॅक्स',
      'nav_settings': 'सेटिंग्ज',
      'settings_title': 'सेटिंग्ज केंद्र',
      'settings_account_info': 'खाते माहिती',
      'settings_member': 'सत्यापित वांगडी',
      'settings_system_toggles': 'सिस्टम आनी टॉगल',
      'settings_sms_title': 'स्वयंचलित एसएमएस पार्सिंग',
      'settings_sms_sub': 'फाटभुंयेर वित्तीय पावती एसएमएस प्रक्रिया करात',
      'settings_imports_title': 'स्वयंचलित स्टेटमेंट आयात',
      'settings_imports_sub': 'CSV आनी मजकूर स्टेटमेंट रूपांतरणाक परवानगी दितात',
      'settings_notif_title': 'सूचना इतिहास साठयात',
      'settings_notif_sub': 'इन-अॅप सूचना थळाव्या इतिहासांत साठयात',
      'settings_biometric_title': 'बायोमेट्रिक लॉक स्क्रीन',
      'settings_biometric_sub': 'अॅप सुरू करतना बोटाचे ठसे/फेस आयडी विचारात',
      'settings_monetization': 'मॉनेटीकरण आनी स्टार्टअप वाड',
      'settings_upgrade': 'गिगटॅक्स प्रोचेर अपग्रेड करात',
      'settings_upgrade_sub': 'व्हॉट-इफ सिम्युलेटर, थळावे एआय टॅक्स सल्लागार आनी अमर्यादित पीडीएफ मेळयात',
      'settings_founder': 'संस्थापक कमांड सेंटर',
      'settings_founder_sub': 'स्टार्टअप भलायकी, ग्राहक धारणा आनी आदार तिकटी',
      'settings_support': 'आदार तिकीट आनी अभिप्राय धाडात',
      'settings_support_sub': 'अणभवाक मानांकन दितात, बग अहवाल धाडात',
      'settings_referral': 'रेफरल कार्यक्रम आनी इनाम',
      'settings_referral_sub': 'तुमचो रेफरल कोड वांटात आनी ₹५०० प्रो क्रेडिट मेळयात',
      'settings_storage': 'स्टोरेज आनी व्यवस्थापन',
      'settings_clear_logs': 'व्यवहार लॉग साफ करात',
      'settings_clear_logs_sub': 'सगळे थळावे आनी कॅश केल्ले व्यवहार रेकॉर्ड काडून उडयात',
      'settings_import_mock': 'चाचणी डेटा आयात करात',
      'settings_import_mock_sub': 'चाचणी खातीर ६+ बनावट पावतयो जोडात',
      'tax_report_center': 'टॅक्स रिपोर्ट केंद्र (CA-Ready)',
      'tax_report_sub': 'तुमच्या वेवसायाचे गरजे प्रमाणे पीडीएफ डाऊनलोड करात.',
      'tax_generate_btn': 'अहवाल तयार करात आनी डाऊनलोड करात',
    },
    'mai': {
      'app_title': 'गिगटैक्स (GigTax)',
      'nav_home': 'घर',
      'nav_analytics': 'विश्लेषण',
      'nav_receipts': 'रसीद',
      'nav_tax': 'टैक्स',
      'nav_settings': 'सेटिंग्स',
      'settings_title': 'सेटिंग्स केंद्र',
      'settings_account_info': 'खाताक जानकारी',
      'settings_member': 'सत्यापित सदस्य',
      'settings_system_toggles': 'सिस्टम आ टॉगल',
      'settings_sms_title': 'स्वचालित एसएमएस पार्सिंग',
      'settings_sms_sub': 'बैकग्राउंड में वित्तीय रसीद एसएमएस प्रोग्रेस करू',
      'settings_imports_title': 'स्वचालित स्टेटमेंट आयात',
      'settings_imports_sub': 'CSV आ टेक्स्ट स्टेटमेंट कन्वर्शनक मंजूरी दियौ',
      'settings_notif_title': 'सूचनाक इतिहास सुरक्षित करू',
      'settings_notif_sub': 'इन-ऐप सूचना के स्थानीय इतिहास में रखू',
      'settings_biometric_title': 'बायोमेट्रिक लॉक स्क्रीन',
      'settings_biometric_sub': 'ऐप शुरू होय पर फिंगरप्रिंट/फेस आईडी मंगू',
      'settings_monetization': 'मुद्रीकरण आ स्टार्टअप विकास',
      'settings_upgrade': 'गिगटैक्स प्रो में अपग्रेड करू',
      'settings_upgrade_sub': 'वॉट-इफ सिम्युलेटर, स्थानीय एआई टैक्स सलाहकार आ असीमित पीडीएफ पाबू',
      'settings_founder': 'संस्थापक कमांड सेंटर',
      'settings_founder_sub': 'स्टार्टअप स्वास्थ्य, ग्राहक प्रतिधारण आ सहायता टिकट',
      'settings_support': 'सहायता टिकट आ फीडबैक भेजूं',
      'settings_support_sub': 'अनुभव के रेट करू, बग रिपोर्ट सबमिट करू',
      'settings_referral': 'रेफरल कार्यक्रम आ इनाम',
      'settings_referral_sub': 'अपन रेफरल कोड साझा करू आ ₹५०० प्रो क्रेडिट कमाऊ',
      'settings_storage': 'स्टोरेज आ प्रबंधन',
      'settings_clear_logs': 'लेनदेन लॉग साफ करू',
      'settings_clear_logs_sub': 'सबहि स्थानीय आ कैश्ड लेनदेन रिकॉर्ड हटाऊ',
      'settings_import_mock': 'टेस्ट डेटा आयात करू',
      'settings_import_mock_sub': 'डैशबोर्ड टेस्टिंग लेल ६+ मॉक रसीद जोड़ू',
      'tax_report_center': 'टैक्स रिपोर्ट केंद्र (CA-Ready)',
      'tax_report_sub': 'अपन व्यापारिक जरूरतक अनुसार पीडीएफ डाउनलोड करू।',
      'tax_generate_btn': 'रिपोर्ट बनाऊ आ डाउनलोड करू',
    },
    'ml': {
      'app_title': 'ഗിഗ്ടാക്സ് (GigTax)',
      'nav_home': 'ഹോം',
      'nav_analytics': 'വിശകലനം',
      'nav_receipts': 'രസീതുകൾ',
      'nav_tax': 'നികുതി',
      'nav_settings': 'സെറ്റിംഗ്സ്',
      'settings_title': 'സെറ്റിംഗ്സ് കേന്ദ്രം',
      'settings_account_info': 'അക്കൗണ്ട് വിവരങ്ങൾ',
      'settings_member': 'സ്ഥിരീകരിച്ച അംഗം',
      'settings_system_toggles': 'സിസ്റ്റം & ടോഗിളുകൾ',
      'settings_sms_title': 'സ്വയമേവയുള്ള എസ്എംഎസ് പാർസിംഗ്',
      'settings_sms_sub': 'പശ്ചാത്തലത്തിൽ സാമ്പത്തിക രസീത് എസ്എംഎസ് പ്രോസസ്സ് ചെയ്യുക',
      'settings_imports_title': 'സ്വയമേവയുള്ള സ്റ്റേറ്റ്മെന്റ് ഇറക്കുമതി',
      'settings_imports_sub': 'CSV, ടെക്സ്റ്റ് സ്റ്റേറ്റ്മെന്റ് പരിവർത്തനങ്ങൾ അനുവദിക്കുക',
      'settings_notif_title': 'അറിയിപ്പ് ചരിത്രം സംരക്ഷിക്കുക',
      'settings_notif_sub': 'ഇൻ-ആപ്പ് അറിയിപ്പുകൾ പ്രാദേശിക ചരിത്രത്തിൽ സൂക്ഷിക്കുക',
      'settings_biometric_title': 'ബയോമെട്രിക് ലോക്ക് സ്ക്രീൻ',
      'settings_biometric_sub': 'ആപ്പ് ആരംഭിക്കുമ്പോൾ വിരലടയാളം/ഫേസ് ഐഡി ആവശ്യപ്പെടുക',
      'settings_monetization': 'ധനസമ്പാദനവും സ്റ്റാർട്ടപ്പ് വളർച്ചയും',
      'settings_upgrade': 'ഗിഗ്ടാക്സ് പ്രോയിലേക്ക് അപ്ഗ്രേഡ് ചെയ്യുക',
      'settings_upgrade_sub': 'വാട്ട്-ഇഫ് സിമുലേറ്റർ, പ്രാദേശിക എഐ നികുതി ഉപദേശകൻ, പരിധിയില്ലാത്ത പിഡിഎഫ് എന്നിവ നേടുക',
      'settings_founder': 'സ്ഥാപക കമാൻഡ് സെന്റർ',
      'settings_founder_sub': 'സ്റ്റാർട്ടപ്പ് ആരോഗ്യം, ഉപഭോക്തൃ നിലനിർത്തൽ, പിന്തുണ ടിക്കറ്റുകൾ',
      'settings_support': 'പിന്തുണ ടിക്കറ്റും ഫീഡ്ബാക്കും സമർപ്പിക്കുക',
      'settings_support_sub': 'അനുഭവം റേറ്റുചെയ്യുക അല്ലെങ്കിൽ പിന്തുണയുമായി ബന്ധപ്പെടുക',
      'settings_referral': 'റഫറൽ പ്രോഗ്രാമും പ്രതിഫലങ്ങളും',
      'settings_referral_sub': 'നിങ്ങളുടെ റഫറൽ കോഡ് പങ്കിട്ട് ₹൫൦൦ പ്രോ ക്രെഡിറ്റ് നേടുക',
      'settings_storage': 'സംഭരണവും മാനേജ്മെന്റും',
      'settings_clear_logs': 'ഇടപാട് ലോഗുകൾ മായ്ക്കുക',
      'settings_clear_logs_sub': 'എല്ലാ പ്രാദേശിക, കാഷെ ചെയ്ത ഇടപാട് രേഖകളും മായ്ക്കുക',
      'settings_import_mock': 'ടെസ്റ്റ് ഡാറ്റ ഇറക്കുമതി ചെയ്യുക',
      'settings_import_mock_sub': 'ടെസ്റ്റിംഗിനായി 6+ മോക്ക് രസീതുകൾ ചേർക്കുക',
      'tax_report_center': 'നികുതി റിപ്പോർട്ട് കേന്ദ്രം (CA-Ready)',
      'tax_report_sub': 'നിങ്ങളുടെ ബിസിനസ്സ് ആവശ്യങ്ങൾക്ക് അനുയോജ്യമായ പിഡിഎഫ് ഡൗൺലോഡ് ചെയ്യുക.',
      'tax_generate_btn': 'റിപ്പോർട്ട് സൃഷ്ടിച്ച് ഡൗൺലോഡ് ചെയ്യുക',
    }
  };

  String translate(String key) {
    return _localizedValues[_currentLocale]?[key] ?? key;
  }
}
