import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  static const Map<String, String> supportedLocales = {
    'en': 'English',
    'hi': 'हिन्दी (Hindi)',
    'as': 'অসমীয়া (Assamese)',
    'bn': 'বাংলা (Bengali)',
    'brx': 'बरो (Bodo)',
    'doi': 'डोगरी (Dogri)',
    'gu': 'ગુજરાતી (Gujarati)',
    'kn': 'ಕನ್ನಡ (Kannada)',
    'ks': 'کٲشূর (Kashmiri)',
    'kok': 'कोंकणी (Konkani)',
    'mai': 'मैथिली (Maithili)',
    'ml': 'മലയാളം (Malayalam)',
    'mni': 'মৈতৈলোন (Manipuri)',
    'mr': 'मराठी (Marathi)',
    'ne': 'नेपाली (Nepali)',
    'or': 'ଓଡ଼ିଆ (Odia)',
    'pa': 'ਪੰਜਾਬੀ (Punjabi)',
    'sa': 'संस्कृतम् (Sanskrit)',
    'sat': 'ᱥᱟᱱᱛᱟᱲᱤ (Santali)',
    'sd': 'سنڌي (Sindhi)',
    'ta': 'தமிழ் (Tamil)',
    'te': 'తెలుగు (Telugu)',
    'ur': 'اردو (Urdu)',
  };

  String _currentLocale = 'en';

  String get currentLocale => _currentLocale;

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLocale = prefs.getString('app_language_locale') ?? 'en';
    notifyListeners();
  }

  Future<void> setLanguage(String locale) async {
    if (locale == _currentLocale) return;
    _currentLocale = locale;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('app_language_locale', locale);
    notifyListeners();
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'GigTax',
      'nav_home': 'Home',
      'nav_analytics': 'Analytics',
      'nav_receipts': 'Receipts',
      'nav_tax': 'Tax',
      'nav_settings': 'Settings',
      'settings_title': 'Settings Center',
      'settings_account_info': 'Account Info',
      'settings_member': 'Verified Member',
      'settings_system_toggles': 'System & Toggles',
      'settings_sms_title': 'Automatic SMS Parsing',
      'settings_sms_sub': 'Process financial receipt SMS in the background',
      'settings_imports_title': 'Automatic Statement Imports',
      'settings_imports_sub': 'Allow CSV & text statement conversions',
      'settings_notif_title': 'Save Notification History',
      'settings_notif_sub': 'Store in-app notifications in local history',
      'settings_biometric_title': 'Biometric Lock Screen',
      'settings_biometric_sub': 'Prompt for fingerprint/FaceID on app startup',
      'settings_monetization': 'Monetization & Startup Growth',
      'settings_upgrade': 'Upgrade to GigTax Pro',
      'settings_upgrade_sub': 'Access What-If simulator, local AI tax advisor, and unlimited PDF exports',
      'settings_founder': 'Founder Command Center',
      'settings_founder_sub': 'Real-time startup health, user retention cohorts, support tickets, and performance indicators',
      'settings_support': 'Submit Support Ticket & Feedback',
      'settings_support_sub': 'Rate experience, submit bug reports, feature requests, or contact support',
      'settings_referral': 'Referral Program & Rewards',
      'settings_referral_sub': 'Share your referral code and earn ₹500 in Pro credits',
      'settings_storage': 'Storage & Management',
      'settings_clear_logs': 'Clear Transaction Logs',
      'settings_clear_logs_sub': 'Wipe out all local and cached transactional records',
      'settings_import_mock': 'Import Test Data',
      'settings_import_mock_sub': 'Add 6+ mock transaction receipts for dashboard testing',
      'tax_report_center': 'Tax Report Center (CA-Ready)',
      'tax_report_sub': 'Download dedicated PDF logs matching your business requirements.',
      'tax_generate_btn': 'Generate and Download Report',
    },
    'hi': {
      'app_title': 'गिगटैक्स (GigTax)',
      'nav_home': 'होम',
      'nav_analytics': 'एनालिटिक्स',
      'nav_receipts': 'रसीदें',
      'nav_tax': 'टैक्स',
      'nav_settings': 'सेटिंग्स',
      'settings_title': 'सेटिंग्स केंद्र',
      'settings_account_info': 'खाता जानकारी',
      'settings_member': 'सत्यापित सदस्य',
      'settings_system_toggles': 'सिस्टम और टॉगल',
      'settings_sms_title': 'स्वचालित एसएमएस पार्सिंग',
      'settings_sms_sub': 'बैकग्राउंड में वित्तीय रसीद एसएमएस प्रोसेस करें',
      'settings_imports_title': 'स्वचालित स्टेटमेंट इंपोर्ट',
      'settings_imports_sub': 'CSV और टेक्स्ट स्टेटमेंट कन्वर्शन सक्षम करें',
      'settings_notif_title': 'नोटिफिकेशन हिस्ट्री सहेजें',
      'settings_notif_sub': 'इन-ऐप नोटिफिकेशन को लोकल स्टोरेज में सहेजें',
      'settings_biometric_title': 'बायोमेट्रिक लॉक स्क्रीन',
      'settings_biometric_sub': 'ऐप स्टार्टअप पर फिंगरप्रिंट/FaceID मांगें',
      'settings_monetization': 'मुद्रीकरण और स्टार्टअप विकास',
      'settings_upgrade': 'गिगटैक्स प्रो में अपग्रेड करें',
      'settings_upgrade_sub': 'वॉट-इफ सिम्युलेटर, लोकल एआई टैक्स सलाहकार और अनलिमिटेड PDF एक्सपोर्ट पाएं',
      'settings_founder': 'फाउंडर कमांड सेंटर',
      'settings_founder_sub': 'स्टार्टअप स्वास्थ्य, उपयोगकर्ता प्रतिधारण समूह, समर्थन टिकट और प्रदर्शन संकेतक',
      'settings_support': 'सपोर्ट टिकट और फीडबैक भेजें',
      'settings_support_sub': 'अनुभव को रेट करें, बग रिपोर्ट, फीचर अनुरोध सबमिट करें',
      'settings_referral': 'रेफरल कार्यक्रम और पुरस्कार',
      'settings_referral_sub': 'अपना रेफरल कोड साझा करें और ₹500 प्रो क्रेडिट अर्जित करें',
      'settings_storage': 'स्टोरेज और प्रबंधन',
      'settings_clear_logs': 'लेनदेन लॉग्स साफ करें',
      'settings_clear_logs_sub': 'सभी स्थानीय और कैश्ड लेनदेन रिकॉर्ड हटा दें',
      'settings_import_mock': 'टेस्ट डेटा इंपोर्ट करें',
      'settings_import_mock_sub': 'डैशबोर्ड टेस्टिंग के लिए 6+ मॉक रसीदें जोड़ें',
      'tax_report_center': 'टैक्स रिपोर्ट केंद्र (CA-Ready)',
      'tax_report_sub': 'अपनी व्यावसायिक आवश्यकताओं के अनुसार समर्पित PDF लॉग डाउनलोड करें।',
      'tax_generate_btn': 'रिपोर्ट बनाएं और डाउनलोड करें',
    },
    'as': {
      'app_title': 'গিগট্যাক্স (GigTax)',
      'nav_home': 'ঘৰ',
      'nav_analytics': 'বিশ্লেষণ',
      'nav_receipts': 'ৰচিদসমূহ',
      'nav_tax': 'কৰ',
      'nav_settings': 'ছেটিংছ',
      'settings_title': 'ছেটিংছ কেন্দ্ৰ',
      'settings_account_info': 'অ্যাকাউন্ট তথ্য',
      'settings_member': 'যাচাই কৰা সদস্য',
      'settings_system_toggles': 'ছিষ্টেম টগলসমূহ',
      'settings_sms_title': 'স্বয়ংক্ৰিয় এছএমএছ বিশ্লেষণ',
      'settings_sms_sub': 'পৃষ্ঠভূমিত বিত্তীয় ৰচিদৰ এছএমএছ প্ৰক্ৰিয়াকৰণ কৰক',
      'settings_imports_title': 'স্বয়ংক্ৰিয় বিবৃতি আমদানি',
      'settings_imports_sub': 'CSV আৰু পাঠ্য বিবৃতি ৰূপান্তৰৰ অনুমতি দিয়ক',
      'settings_notif_title': 'জাননী ইতিহাস সংৰক্ষণ কৰক',
      'settings_notif_sub': 'ইন-এপ জাননীসমূহ স্থানীয় ইতিহাসত সংৰক্ষণ কৰক',
      'settings_biometric_title': 'বায়োমেট্ৰিক লক স্ক্ৰীণ',
      'settings_biometric_sub': 'এপ আৰম্ভণিতে আঙুলিৰ ছাপ/ফেচ আই ডি বিচাৰক',
      'settings_monetization': 'মুদ্ৰাকৰণ আৰু ষ্টাৰ্টআপ বৃদ্ধি',
      'settings_upgrade': 'গিগট্যাক্স প্ৰোলৈ উন্নীত কৰক',
      'settings_upgrade_sub': 'হোৱাট-ইফ চিমুলেটৰ, স্থানীয় এআই কৰ পৰামৰ্শদাতা, আৰু সীমাহীন পিডিএফ ৰিপোৰ্ট লাভ কৰক',
      'settings_founder': 'প্ৰতিষ্ঠাপক কমাণ্ড কেন্দ্ৰ',
      'settings_founder_sub': 'ষ্টাৰ্টআপৰ স্বাস্থ্য, ব্যৱহাৰকাৰীৰ ধৰি ৰখা কোহোৰ্ট, আৰু সমৰ্থন টিকটসমূহ',
      'settings_support': 'সমৰ্থন টিকট আৰু মতামত প্ৰেৰণ কৰক',
      'settings_support_sub': 'অভিজ্ঞতা মূল্যাংকন কৰক, বা সমৰ্থনৰ সৈতে যোগাযোগ কৰক',
      'settings_referral': 'ৰেফাৰেল কাৰ্যসূচী আৰু পুৰস্কাৰ',
      'settings_referral_sub': 'আপোনাৰ ৰেফাৰেল ক’ড শ্বেয়াৰ কৰক আৰু ₹৫০০ লাভ কৰক',
      'settings_storage': 'সংৰক্ষণ আৰু ব্যৱস্থাপনা',
      'settings_clear_logs': 'লেনদেন লগসমূহ মচি পেলাওক',
      'settings_clear_logs_sub': 'সকলো স্থানীয় লেনদেনৰ ৰেকৰ্ড মচি পেলাওক',
      'settings_import_mock': 'পৰীক্ষামূলক তথ্য আমদানি কৰক',
      'settings_import_mock_sub': 'ড্যাশবৰ্ড পৰীক্ষাৰ বাবে ৬+ মক ৰচিদ যোগ কৰক',
      'tax_report_center': 'কৰ ৰিপোৰ্ট কেন্দ্ৰ (CA-Ready)',
      'tax_report_sub': 'আপোনাৰ ব্যৱসায়িক প্ৰয়োজনীয়তাৰ সৈতে খাপ খোৱা পিডিএফ সংৰক্ষণ কৰক।',
      'tax_generate_btn': 'ৰিপোৰ্ট প্ৰস্তুত আৰু ডাউনলোড কৰক',
    },
    'bn': {
      'app_title': 'গিগট্যাক্স (GigTax)',
      'nav_home': 'হোম',
      'nav_analytics': 'বিশ্লেষণ',
      'nav_receipts': 'রসিদসমূহ',
      'nav_tax': 'কর',
      'nav_settings': 'সেটিংস',
      'settings_title': 'সেটিংস সেন্টার',
      'settings_account_info': 'অ্যাকাউন্টের তথ্য',
      'settings_member': 'যাচাইকৃত সদস্য',
      'settings_system_toggles': 'সিস্টেম ও টগল',
      'settings_sms_title': 'স্বয়ংক্রিয় এসএমএস পার্সিং',
      'settings_sms_sub': 'ব্যাকগ্রাউন্ডে আর্থিক রসিদ এসএমএস প্রসেস করুন',
      'settings_imports_title': 'স্বয়ংক্রিয় স্টেটমেন্ট ইম্পোর্ট',
      'settings_imports_sub': 'CSV ও টেক্সট স্টেটমেন্ট রূপান্তর সক্ষম করুন',
      'settings_notif_title': 'নোটিফিকেশন ইতিহাস সংরক্ষণ করুন',
      'settings_notif_sub': 'ইন-অ্যাপ নোটিফিকেশন স্থানীয় ইতিহাসে সংরক্ষণ করুন',
      'settings_biometric_title': 'বায়োমেট্রিক লক স্ক্রিন',
      'settings_biometric_sub': 'অ্যাপ চালুর সময় ফিঙ্গারপ্রিন্ট/ফেস আইডি প্রম্পট করুন',
      'settings_monetization': 'মনিটাইজেশন ও স্টার্টআপ বৃদ্ধি',
      'settings_upgrade': 'গিগট্যাক্স প্রো-তে আপগ্রেড করুন',
      'settings_upgrade_sub': 'হোয়াট-ইফ সিমুলেটর, স্থানীয় এআই ট্যাক্স উপদেষ্টা এবং আনলিমিটেড পিডিএফ পান',
      'settings_founder': 'প্রতিষ্ঠাতা কমান্ড সেন্টার',
      'settings_founder_sub': 'স্টার্টআপের স্বাস্থ্য, ব্যবহারকারী ধারণ কোহর্ট এবং সমর্থন টিকিট',
      'settings_support': 'সহায়তা টিকিট ও মতামত পাঠান',
      'settings_support_sub': 'অভিজ্ঞতা রেট করুন বা সহায়তার সাথে যোগাযোগ করুন',
      'settings_referral': 'রেফারেল প্রোগ্রাম ও পুরস্কার',
      'settings_referral_sub': 'আপনার রেফারেল কোড শেয়ার করুন এবং ₹৫০০ প্রফিট ক্রেডিট পান',
      'settings_storage': 'স্টোরেজ ও ম্যানেজমেন্ট',
      'settings_clear_logs': 'লেনদেনের লগ মুছে ফেলুন',
      'settings_clear_logs_sub': 'সব স্থানীয় এবং ক্যাশ লেনদেন রেকর্ড মুছে ফেলুন',
      'settings_import_mock': 'পরীক্ষামূলক ডেটা ইম্পোর্ট করুন',
      'settings_import_mock_sub': 'ড্যাশবোর্ড পরীক্ষার জন্য ৬+ মক রসিদ যোগ করুন',
      'tax_report_center': 'কর রিপোর্ট কেন্দ্র (CA-Ready)',
      'tax_report_sub': 'আপনার ব্যবসায়িক প্রয়োজন অনুযায়ী পিডিএফ ডাউনলোড করুন।',
      'tax_generate_btn': 'রিপোর্ট তৈরি ও ডাউনলোড করুন',
    },
    'brx': {
      'app_title': 'गिगटैक्स (GigTax)',
      'nav_home': 'नोगो',
      'nav_analytics': 'बिजिरनाय',
      'nav_receipts': 'रसिदफोर',
      'nav_tax': 'टैक्स',
      'nav_settings': 'सेटिंगफोर',
      'settings_title': 'सेटिंग सेंटर',
      'settings_account_info': 'खाता मिथिसारनाय',
      'settings_member': 'गोनायथि जानाय सोद्रोमा',
      'settings_system_toggles': 'सिस्टम आरो टगलफोर',
      'settings_sms_title': 'गावनोगावनो एसएमएस पार्सिंग',
      'settings_sms_sub': 'बैकग्राउंडआव रांआरि रसिद एसएमएस प्रसेस खालाम',
      'settings_imports_title': 'गावनोगावनो स्टेटमेन्ट इम्पोर्ट',
      'settings_imports_sub': 'CSV आरो टेक्स्ट स्टेटमेन्ट सोलायनायखौ गनायथि हो',
      'settings_notif_title': 'फोरमायनाय जारिमिन लाखि',
      'settings_notif_sub': 'इन-एप फोरमायनायफोरखौ जायगायाव लाखि',
      'settings_biometric_title': 'बायोमेट्रिक लक स्क्रिन',
      'settings_biometric_sub': 'एप जागायनायाव फिंगरप्रिन्ट/फेस आइडी नागिर',
      'settings_monetization': 'रां खालामनाय आरो जागायनाय बाढायनाय',
      'settings_upgrade': 'गिगटैक्स प्रो आव अपग्रेड खालाम',
      'settings_upgrade_sub': 'वॉट-इफ सिम्युलेटर, जायगायाव एआई टैक्स सुबहागिरि आरो अनलिमिटेड पीडीएफ मोनो',
      'settings_founder': 'गायसलग कमांड सेंटर',
      'settings_founder_sub': 'स्टार्टআপ गोख्रोंथि, बाहायगिरि जारिमिन आरो मदद टिकटफोर',
      'settings_support': 'मदद टिकट आरो फीडबैक हर',
      'settings_support_sub': 'रोंमोननायखौ रेट खालाम, बग रिपोर्ट सबमिट खालाम',
      'settings_referral': 'रेफरल कार्यक्रम आरो बान्थाफोर',
      'settings_referral_sub': 'नोङोनि रेफरल कोडखौ रान आरो ₹५०० प्रो क्रेडिट मोनो',
      'settings_storage': 'स्टोरेज आरो सामलायनाय',
      'settings_clear_logs': 'लेनदेन लोगफोरखौ साखोन-सिखोन खालाम',
      'settings_clear_logs_sub': 'गासैबो जायगायाव थानाय लेनदेन रेकर्डफोरखौ हुगार',
      'settings_import_mock': 'आनजाद डेटा इम्पोर्ट खालाम',
      'settings_import_mock_sub': 'डैशबोर्ड आनजाद खालामनो थाखाय ६+ नंखाय रसिदफोर दाजाब',
      'tax_report_center': 'टैक्स रिपोर्ट सेंटर (CA-Ready)',
      'tax_report_sub': 'नोङोनि फालांगि गोनांथियै पीडीएफ डाउनलोड खालाम।',
      'tax_generate_btn': 'रिपोर्ट दा आरो डाउनलोड खालाम',
    },
    'doi': {
      'app_title': 'गिगटैक्स (GigTax)',
      'nav_home': 'घर',
      'nav_analytics': 'विश्लेषण',
      'nav_receipts': 'रसीदां',
      'nav_tax': 'टैक्स',
      'nav_settings': 'सेटिंग्स',
      'settings_title': 'सेटिंग्स केंद्र',
      'settings_account_info': 'खाता जानकारी',
      'settings_member': 'सत्यापित सदस्य',
      'settings_system_toggles': 'सिस्टम ते टॉगल',
      'settings_sms_title': 'स्वचालित एसएमएस पार्सिंग',
      'settings_sms_sub': 'बैकग्राउंड च वित्तीय रसीद एसएमएस प्रोग्रेस करो',
      'settings_imports_title': 'स्वचालित स्टेटमेंट इंपोर्ट',
      'settings_imports_sub': 'CSV ते टेक्स्ट स्टेटमेंट कन्वर्शन दी मंजूरी देओ',
      'settings_notif_title': 'सूचना इतिहास सँभालो',
      'settings_notif_sub': 'इन-ऐप सूचना गी स्थानीय स्टोरेज च रखो',
      'settings_biometric_title': 'बायोमेट्रिक लॉक स्क्रीन',
      'settings_biometric_sub': 'ऐप शुरू होन पर उंगली दा निशान/फेस आईडी पूछो',
      'settings_monetization': 'मुद्रीकरण ते स्टार्टअप विकास',
      'settings_upgrade': 'गिगटैक्स प्रो च अपग्रेड करो',
      'settings_upgrade_sub': 'वॉट-इफ सिम्युलेटर, लोकल एआई टैक्स सलाहकार ते असीमित पीडीएफ पाओ',
      'settings_founder': 'संस्थापक कमांड सेंटर',
      'settings_founder_sub': 'स्टार्टअप सेहत, उपभोक्ता प्रतिधारण समूह ते सहायता टिकट',
      'settings_support': 'सहायता टिकट ते फीडबैक देओ',
      'settings_support_sub': 'अनुभव गी रेट करो, बग रिपोर्ट सबमिट करो',
      'settings_referral': 'रेफरल कार्यक्रम ते इनाम',
      'settings_referral_sub': 'अपना रेफरल कोड सांझा करो ते ₹५०० प्रो क्रेडिट कमाओ',
      'settings_storage': 'स्टोरेज ते प्रबंधन',
      'settings_clear_logs': 'लेनदेन लॉग साफ करो',
      'settings_clear_logs_sub': 'सारे स्थानीय ते कैश्ड लेनदेन रिकॉर्ड हटाओ',
      'settings_import_mock': 'टेस्ट डेटा इंपोर्ट करो',
      'settings_import_mock_sub': 'डैशबोर्ड टेस्टिंग लेई ६+ मॉक रसीदां जोड़ो',
      'tax_report_center': 'टैक्स रिपोर्ट केंद्र (CA-Ready)',
      'tax_report_sub': 'अपनी व्यापारिक जरूरतें दे अनुसार समर्पित पीडीएफ डाउनलोड करो।',
      'tax_generate_btn': 'रिपोर्ट बनाओ ते डाउनलोड करो',
    },
    'gu': {
      'app_title': 'ગીગટેક્સ (GigTax)',
      'nav_home': 'હોમ',
      'nav_analytics': 'વિશ્લેષણ',
      'nav_receipts': 'રસીદો',
      'nav_tax': 'ટેક્સ',
      'nav_settings': 'સેટિંગ્સ',
      'settings_title': 'સેટિંગ્સ સેન્ટર',
      'settings_account_info': 'ખાતાની માહિતી',
      'settings_member': 'ચકાસાયેલ સભ્ય',
      'settings_system_toggles': 'સિસ્ટમ અને ટૉગલ્સ',
      'settings_sms_title': 'સ્વચાલિત એસએમએસ વિશ્લેષણ',
      'settings_sms_sub': 'બેકગ્રાઉન્ડમાં નાણાકીય રસીદ એસએમએસ પ્રોસેસ કરો',
      'settings_imports_title': 'સ્વચાલિત સ્ટેટમેન્ટ આયાત',
      'settings_imports_sub': 'CSV અને ટેક્સ્ટ સ્ટેટમેન્ટ કન્વર્ઝનની મંજૂરી આપો',
      'settings_notif_title': 'નોટિફિકેશન ઇતિહાસ સાચવો',
      'settings_notif_sub': 'ઇન-એપ નોટિફિકેશન સ્થાનિક ઇતિહાસમાં સંગ્રહિત કરો',
      'settings_biometric_title': 'બાયોમેટ્રિક લોક સ્ક્રીન',
      'settings_biometric_sub': 'એપ શરૂ થાય ત્યારે ફિંગરપ્રિન્ટ/ફેસ આઈડી માટે પૂછો',
      'settings_monetization': 'મોનેટાઇઝેશન અને સ્ટાર્ટઅપ વિકાસ',
      'settings_upgrade': 'ગીગટેક્સ પ્રો પર અપગ્રેડ કરો',
      'settings_upgrade_sub': 'વૉટ-ઇફ સિમ્યુલેટર, સ્થાનિક એઆઈ ટેક્સ સલાહકાર અને અમર્યાદિત પીડીએફ મેળવો',
      'settings_founder': 'સ્થાપક કમાન્ડ સેન્ટર',
      'settings_founder_sub': 'સ્ટાર્ટઅપ સ્વાસ્થ્ય, વપરાશકર્તા રીટેન્શન અને સપોર્ટ ટિકિટ્સ',
      'settings_support': 'સપોર્ટ ટિકિટ અને ફીડબેક મોકલો',
      'settings_support_sub': 'અનુભવ રેટ કરો, બગ રિપોર્ટ સબમિટ કરો અથવા સંપર્ક કરો',
      'settings_referral': 'રેફરલ પ્રોગ્રામ અને પુરસ્કારો',
      'settings_referral_sub': 'તમારો રેફરલ કોડ શેર કરો અને ₹૫૦૦ પ્રો ક્રેડિટ મેળવો',
      'settings_storage': 'સ્ટોરેજ અને મેનેજમેન્ટ',
      'settings_clear_logs': 'વ્યવહાર લોગ્સ સાફ કરો',
      'settings_clear_logs_sub': 'બધા સ્થાનિક અને કેશ્ડ વ્યવહાર રેકોર્ડ્સ ભૂંસી નાખો',
      'settings_import_mock': 'ટેસ્ટ ડેટા આયાત કરો',
      'settings_import_mock_sub': 'ટેસ્ટિંગ માટે ૬+ મોક રસીદો ઉમેરો',
      'tax_report_center': 'ટેક્સ રિપોર્ટ સેન્ટર (CA-Ready)',
      'tax_report_sub': 'તમારા વ્યવસાયની જરૂરિયાતોને અનુરૂપ સમર્પિત પીડીએફ ડાઉનલોડ કરો.',
      'tax_generate_btn': 'રિપોર્ટ બનાવો અને ડાઉનલોડ કરો',
    },
    'kn': {
      'app_title': 'ಗಿಗ್ಟ್ಯಾಕ್ಸ್ (GigTax)',
      'nav_home': 'ಮುಖಪುಟ',
      'nav_analytics': 'ವಿಶ್ಲೇಷಣೆ',
      'nav_receipts': 'ರಸೀದಿಗಳು',
      'nav_tax': 'ತೆರಿಗೆ',
      'nav_settings': 'ಸೆಟ್ಟಿಂಗ್ಸ್',
      'settings_title': 'ಸೆಟ್ಟಿಂಗ್ಸ್ ಕೇಂದ್ರ',
      'settings_account_info': 'ಖಾತೆ ಮಾಹಿತಿ',
      'settings_member': 'ಪರಿಶೀಲಿಸಿದ ಸದಸ್ಯ',
      'settings_system_toggles': 'ಸಿಸ್ಟಮ್ ಮತ್ತು ಟಾಗಲ್‌ಗಳು',
      'settings_sms_title': 'ಸ್ವಯಂಚಾಲಿತ ಎಸ್‌ಎಂಎಸ್ ಪಾರ್ಸಿಂಗ್',
      'settings_sms_sub': 'ಹಿನ್ನೆಲೆಯಲ್ಲಿ ಹಣಕಾಸು ರಸೀದಿ ಎಸ್‌ಎಂಎಸ್‌ಗಳನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಿ',
      'settings_imports_title': 'ಸ್ವಯಂಚಾಲಿತ ಹೇಳಿಕೆ ಆಮದುಗಳು',
      'settings_imports_sub': 'CSV ಮತ್ತು ಪಠ್ಯ ಹೇಳಿಕೆ ಪರಿವರ್ತನೆಗಳನ್ನು ಅನುಮತಿಸಿ',
      'settings_notif_title': 'ಅಧಿಸೂಚನೆ ಇತಿಹಾಸವನ್ನು ಉಳಿಸಿ',
      'settings_notif_sub': 'ಅಪ್ಲಿಕೇಶನ್‌ನಲ್ಲಿನ ಅಧಿಸೂಚನೆಗಳನ್ನು ಸ್ಥಳೀಯ ಇತಿಹಾಸದಲ್ಲಿ ಉಳಿಸಿ',
      'settings_biometric_title': 'ಬಯೋಮೆಟ್ರಿಕ್ ಲಾಕ್ ಸ್ಕ್ರೀನ್',
      'settings_biometric_sub': 'ಅಪ್ಲಿಕೇಶನ್ ಪ್ರಾರಂಭದಲ್ಲಿ ಫಿಂಗರ್‌ಪ್ರಿಂಟ್/ಫೇಸ್ ಐಡಿಗಾಗಿ ಕೇಳಿ',
      'settings_monetization': 'ಮಾನಿಟೈಸೇಶನ್ ಮತ್ತು ಸ್ಟಾರ್ಟ್ಅಪ್ ಬೆಳವಣಿಗೆ',
      'settings_upgrade': 'ಗಿಗ್ಟ್ಯಾಕ್ಸ್ ಪ್ರೊಗೆ ಅಪ್‌ಗ್ರೇಡ್ ಮಾಡಿ',
      'settings_upgrade_sub': 'ವಾಟ್-ಇಫ್ ಸಿಮ್ಯುಲೇಟರ್, ಸ್ಥಳೀಯ ಎಐ ತೆರಿಗೆ ಸಲಹೆಗಾರ ಮತ್ತು ಅನಿಯಮಿತ ಪಿಡಿಎಫ್ ಪಡೆಯಿರಿ',
      'settings_founder': 'ಸ್ಥಾಪಕ ಕಮಾಂಡ್ ಸೆಂಟರ್',
      'settings_founder_sub': 'ಸ್ಟಾರ್ಟ್ಅಪ್ ಆರೋಗ್ಯ, ಬಳಕೆದಾರರ ಧಾರಣ ಮತ್ತು ಬೆಂಬಲ ಟಿಕೆಟ್‌ಗಳು',
      'settings_support': 'ಬೆಂಬಲ ಟಿಕೆಟ್ ಮತ್ತು ಪ್ರತಿಕ್ರಿಯೆ ಸಲ್ಲಿಸಿ',
      'settings_support_sub': 'ಅನುಭವವನ್ನು ರೇಟ್ ಮಾಡಿ, ದೋಷ ವರದಿಗಳನ್ನು ಸಲ್ಲಿಸಿ',
      'settings_referral': 'ರೆಫರಲ್ ಪ್ರೋಗ್ರಾಂ ಮತ್ತು ಬಹುಮಾನಗಳು',
      'settings_referral_sub': 'ನಿಮ್ಮ ರೆಫರಲ್ ಕೋಡ್ ಹಂಚಿಕೊಳ್ಳಿ ಮತ್ತು ₹೫೦೦ ಗಳಿಸಿ',
      'settings_storage': 'ಸಂಗ್ರಹಣೆ ಮತ್ತು ನಿರ್ವಹಣೆ',
      'settings_clear_logs': 'ವಹಿವಾಟು ಲಾಗ್‌ಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ',
      'settings_clear_logs_sub': 'ಎಲ್ಲಾ ಸ್ಥಳೀಯ ಮತ್ತು ಸಂಗ್ರಹಿಸಲಾದ ವಹಿವಾಟು ದಾಖಲೆಗಳನ್ನು ಅಳಿಸಿ',
      'settings_import_mock': 'ಟೆಸ್ಟ್ ಡೇಟಾವನ್ನು ಆಮದು ಮಾಡಿ',
      'settings_import_mock_sub': 'ಟೆಸ್ಟಿಂಗ್‌ಗಾಗಿ ೬+ ಅಣಕು ರಸೀದಿಗಳನ್ನು ಸೇರಿಸಿ',
      'tax_report_center': 'ತೆರಿಗೆ ವರದಿ ಕೇಂದ್ರ (CA-Ready)',
      'tax_report_sub': 'ನಿಮ್ಮ ವ್ಯವಹಾರದ ಅವಶ್ಯಕತೆಗಳಿಗೆ ಅನುಗುಣವಾಗಿ ಪಿಡಿಎಫ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ.',
      'tax_generate_btn': 'ವರದಿಯನ್ನು ರಚಿಸಿ ಮತ್ತು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    },
    'ks': {
      'app_title': 'گگ ٹیکس (GigTax)',
      'nav_home': 'گھر',
      'nav_analytics': 'تجزیہ',
      'nav_receipts': 'رسید',
      'nav_tax': 'ٹیکس',
      'nav_settings': 'ترتیبات',
      'settings_title': 'ترتیبات مرکز',
      'settings_account_info': 'کھاتہ معلومات',
      'settings_member': 'تصدیق شدہ ممبر',
      'settings_system_toggles': 'سستم ترتیبات',
      'settings_sms_title': 'خودکار ایس ایم ایس پارسنگ',
      'settings_sms_sub': 'بیک گراؤنڈ میں مالیاتی رسید ایس ایم ایس پروسیس کریں',
      'settings_imports_title': 'خودکار اسٹیٹمنٹ امپورٹ',
      'settings_imports_sub': 'CSV اور ٹیکسٹ اسٹیٹمنٹ کنورژن کی اجازت دیں',
      'settings_notif_title': 'نوٹیفیکیشن ہسٹری محفوظ کریں',
      'settings_notif_sub': 'ان ایپ نوٹیفیکیشنز کو مقامی ہسٹری میں محفوظ کریں',
      'settings_biometric_title': 'بایومیٹرک لاک اسکرین',
      'settings_biometric_sub': 'ایپ اسٹارٹ اپ پر فنگر پرنٹ/فیس آئی ڈی کا مطالبہ کریں',
      'settings_monetization': 'مونٹائزیشن اور اسٹارٹ اپ ترقی',
      'settings_upgrade': 'گگ ٹیکس پرو میں اپ گریڈ کریں',
      'settings_upgrade_sub': 'واٹ اف سمیلیٹر، مقامی اے آئی ٹیکس مشیر اور لامحدود پی ڈی ایف حاصل کریں',
      'settings_founder': 'مؤسس کمانڈ سینٹر',
      'settings_founder_sub': 'اسٹارٹ اپ صحت، کسٹمر ریٹینشن اور سپورٹ ٹکٹس',
      'settings_support': 'سپورٹ ٹکٹ اور فیڈ بیک جمع کروائیں',
      'settings_support_sub': 'تجربے کی درجہ بندی کریں یا سپورٹ سے رابطہ کریں',
      'settings_referral': 'ریفرل پروگرام اور انعامات',
      'settings_referral_sub': 'اپنا ریفرل کوڈ شیئر کریں اور ₹۵۰۰ پرو کریڈٹ حاصل کریں',
      'settings_storage': 'اسٹوریج اور انتظام',
      'settings_clear_logs': 'ٹرانزیکشن لاگز صاف کریں',
      'settings_clear_logs_sub': 'تمام مقامی اور کیش شدہ ٹرانزیکشن ریکارڈز صاف کریں',
      'settings_import_mock': 'ٹیسٹ ڈیٹا درآمد کریں',
      'settings_import_mock_sub': 'ٹیسٹنگ کے لیے ۶+ فرضی رسیدیں شامل کریں',
      'tax_report_center': 'ٹیکس رپورٹ مرکز (CA-Ready)',
      'tax_report_sub': 'اپنی کاروباری ضروریات کے مطابق پی ڈی ایف ڈاؤن لوڈ کریں۔',
      'tax_generate_btn': 'رپورٹ تیار اور ڈاؤن لوڈ کریں',
    },
    'kok': {
      'app_title': 'गिगटॅक्स (GigTax)',
      'nav_home': 'घर',
      'nav_analytics': 'विश्लेषण',
      'nav_receipts': 'पावती',
      'nav_tax': 'टॅक्स',
      'nav_settings': 'सेटिंग्ज',
      'settings_title': 'सेटिंग्ज केंद्र',
      'settings_account_info': 'खाते माहिती',
      'settings_member': 'सत्यापित वांगडी',
      'settings_system_toggles': 'सिस्टम आनी टॉगल',
      'settings_sms_title': 'स्वयंचलित एसएमएस पार्सिंग',
      'settings_sms_sub': 'फाटभुंयेर वित्तीय पावती एसएमएस प्रक्रिया करात',
      'settings_imports_title': 'स्वयंचलित स्टेटमेंट आयात',
      'settings_imports_sub': 'CSV आनी मजकूर स्टेटमेंट रूपांतरणाक परवानगी दितात',
      'settings_notif_title': 'सूचना इतिहास साठयात',
      'settings_notif_sub': 'इन-अॅप सूचना थळाव्या इतिहासांत साठयात',
      'settings_biometric_title': 'बायोमेट्रिक लॉक स्क्रीन',
      'settings_biometric_sub': 'अॅप सुरू करतना बोटाचे ठसे/फेस आयडी विचारात',
      'settings_monetization': 'मॉनेटीकरण आनी स्टार्टअप वाड',
      'settings_upgrade': 'गिगटॅक्स प्रोचेर अपग्रेड करात',
      'settings_upgrade_sub': 'व्हॉट-इफ सिम्युलेटर, थळावे एआय टॅक्स सल्लागार आनी अमर्यादित पीडीएफ मेळयात',
      'settings_founder': 'संस्थापक कमांड सेंटर',
      'settings_founder_sub': 'स्टार्टअप भलायकी, ग्राहक धारणा आनी आदार तिकटी',
      'settings_support': 'आदार तिकीट आनी अभिप्राय धाडात',
      'settings_support_sub': 'अणभवाक मानांकन दितात, बग अहवाल धाडात',
      'settings_referral': 'रेफरल कार्यक्रम आनी इनाम',
      'settings_referral_sub': 'तुमचो रेफरल कोड वांटात आनी ₹५०० प्रो क्रेडिट मेळयात',
      'settings_storage': 'स्टोरेज आनी व्यवस्थापन',
      'settings_clear_logs': 'व्यवहार लॉग साफ करात',
      'settings_clear_logs_sub': 'सगळे थळावे आनी कॅश केल्ले व्यवहार रेकॉर्ड काडून उडयात',
      'settings_import_mock': 'चाचणी डेटा आयात करात',
      'settings_import_mock_sub': 'चाचणी खातीर ६+ बनावट पावतयो जोडात',
      'tax_report_center': 'टॅक्स रिपोर्ट केंद्र (CA-Ready)',
      'tax_report_sub': 'तुमच्या वेवसायाचे गरजे प्रमाणे पीडीएफ डाऊनलोड करात.',
      'tax_generate_btn': 'अहवाल तयार करात आनी डाऊनलोड करात',
    },
    'mai': {
      'app_title': 'गिगटैक्स (GigTax)',
      'nav_home': 'घर',
      'nav_analytics': 'विश्लेषण',
      'nav_receipts': 'रसीद',
      'nav_tax': 'टैक्स',
      'nav_settings': 'सेटिंग्स',
      'settings_title': 'सेटिंग्स केंद्र',
      'settings_account_info': 'खाताक जानकारी',
      'settings_member': 'सत्यापित सदस्य',
      'settings_system_toggles': 'सिस्टम आ टॉगल',
      'settings_sms_title': 'स्वचालित एसएमएस पार्सिंग',
      'settings_sms_sub': 'बैकग्राउंड में वित्तीय रसीद एसएमएस प्रोग्रेस करू',
      'settings_imports_title': 'स्वचालित स्टेटमेंट आयात',
      'settings_imports_sub': 'CSV आ टेक्स्ट स्टेटमेंट कन्वर्शनक मंजूरी दियौ',
      'settings_notif_title': 'सूचनाक इतिहास सुरक्षित करू',
      'settings_notif_sub': 'इन-ऐप सूचना के स्थानीय इतिहास में रखू',
      'settings_biometric_title': 'बायोमेट्रिक लॉक स्क्रीन',
      'settings_biometric_sub': 'ऐप शुरू होय पर फिंगरप्रिंट/फेस आईडी मंगू',
      'settings_monetization': 'मुद्रीकरण आ स्टार्टअप विकास',
      'settings_upgrade': 'गिगटैक्स प्रो में अपग्रेड करू',
      'settings_upgrade_sub': 'वॉट-इफ सिम्युलेटर, स्थानीय एआई टैक्स सलाहकार आ असीमित पीडीएफ पाबू',
      'settings_founder': 'संस्थापक कमांड सेंटर',
      'settings_founder_sub': 'स्टार्टअप स्वास्थ्य, ग्राहक प्रतिधारण आ सहायता टिकट',
      'settings_support': 'सहायता टिकट आ फीडबैक भेजूं',
      'settings_support_sub': 'अनुभव के रेट करू, बग रिपोर्ट सबमिट करू',
      'settings_referral': 'रेफरल कार्यक्रम आ इनाम',
      'settings_referral_sub': 'अपन रेफरल कोड साझा करू आ ₹५०० प्रो क्रेडिट कमाऊ',
      'settings_storage': 'स्टोरेज आ प्रबंधन',
      'settings_clear_logs': 'लेनदेन लॉग साफ करू',
      'settings_clear_logs_sub': 'सबहि स्थानीय आ कैश्ड लेनदेन रिकॉर्ड हटाऊ',
      'settings_import_mock': 'टेस्ट डेटा आयात करू',
      'settings_import_mock_sub': 'डैशबोर्ड टेस्टिंग लेल ६+ मॉक रसीद जोड़ू',
      'tax_report_center': 'टैक्स रिपोर्ट केंद्र (CA-Ready)',
      'tax_report_sub': 'अपन व्यापारिक जरूरतक अनुसार पीडीएफ डाउनलोड करू।',
      'tax_generate_btn': 'रिपोर्ट बनाऊ आ डाउनलोड करू',
    },
    'ml': {
      'app_title': 'ഗിഗ്ടാക്സ് (GigTax)',
      'nav_home': 'ഹോം',
      'nav_analytics': 'വിശകലനം',
      'nav_receipts': 'രസീതുകൾ',
      'nav_tax': 'നികുതി',
      'nav_settings': 'സെറ്റിംഗ്സ്',
      'settings_title': 'സെറ്റിംഗ്സ് കേന്ദ്രം',
      'settings_account_info': 'അക്കൗണ്ട് വിവരങ്ങൾ',
      'settings_member': 'സ്ഥിരീകരിച്ച അംഗം',
      'settings_system_toggles': 'സിസ്റ്റം & ടോഗിളുകൾ',
      'settings_sms_title': 'സ്വയമേവയുള്ള എസ്എംഎസ് പാർസിംഗ്',
      'settings_sms_sub': 'പശ്ചാത്തലത്തിൽ സാമ്പത്തിക രസീത് എസ്എംഎസ് പ്രോസസ്സ് ചെയ്യുക',
      'settings_imports_title': 'സ്വയമേവയുള്ള സ്റ്റേറ്റ്മെന്റ് ഇറക്കുമതി',
      'settings_imports_sub': 'CSV, ടെക്സ്റ്റ് സ്റ്റേറ്റ്മെന്റ് പരിവർത്തനങ്ങൾ അനുവദിക്കുക',
      'settings_notif_title': 'അറിയിപ്പ് ചരിത്രം സംരക്ഷിക്കുക',
      'settings_notif_sub': 'ഇൻ-ആപ്പ് അറിയിപ്പുകൾ പ്രാദേശിക ചരിത്രത്തിൽ സൂക്ഷിക്കുക',
      'settings_biometric_title': 'ബയോമെട്രിക് ലോക്ക് സ്ക്രീൻ',
      'settings_biometric_sub': 'ആപ്പ് ആരംഭിക്കുമ്പോൾ വിരലടയാളം/ഫേസ് ഐഡി ആവശ്യപ്പെടുക',
      'settings_monetization': 'ധനസമ്പാദനവും സ്റ്റാർട്ടപ്പ് വളർച്ചയും',
      'settings_upgrade': 'ഗിഗ്ടാക്സ് പ്രോയിലേക്ക് അപ്ഗ്രേഡ് ചെയ്യുക',
      'settings_upgrade_sub': 'വാട്ട്-ഇഫ് സിമുലേറ്റർ, പ്രാദേശിക എഐ നികുതി ഉപദേശകൻ, പരിധിയില്ലാത്ത പിഡിഎഫ് എന്നിവ നേടുക',
      'settings_founder': 'സ്ഥാപക കമാൻഡ് സെന്റർ',
      'settings_founder_sub': 'സ്റ്റാർട്ടപ്പ് ആരോഗ്യം, ഉപഭോക്തൃ നിലനിർത്തൽ, പിന്തുണ ടിക്കറ്റുകൾ',
      'settings_support': 'പിന്തുണ ടിക്കറ്റും ഫീഡ്ബാക്കും സമർപ്പിക്കുക',
      'settings_support_sub': 'അനുഭവം റേറ്റുചെയ്യുക അല്ലെങ്കിൽ പിന്തുണയുമായി ബന്ധപ്പെടുക',
      'settings_referral': 'റഫറൽ പ്രോഗ്രാമും പ്രതിഫലങ്ങളും',
      'settings_referral_sub': 'നിങ്ങളുടെ റഫറൽ കോഡ് പങ്കിട്ട് ₹൫൦൦ പ്രോ ക്രെഡിറ്റ് നേടുക',
      'settings_storage': 'സംഭരണവും മാനേജ്മെന്റും',
      'settings_clear_logs': 'ഇടപാട് ലോഗുകൾ മായ്ക്കുക',
      'settings_clear_logs_sub': 'എല്ലാ പ്രാദേശിക, കാഷെ ചെയ്ത ഇടപാട് രേഖകളും മായ്ക്കുക',
      'settings_import_mock': 'ടെസ്റ്റ് ഡാറ്റ ഇറക്കുമതി ചെയ്യുക',
      'settings_import_mock_sub': 'ടെസ്റ്റിംഗിനായി 6+ മോക്ക് രസീതുകൾ ചേർക്കുക',
      'tax_report_center': 'നികുതി റിപ്പോർട്ട് കേന്ദ്രം (CA-Ready)',
      'tax_report_sub': 'നിങ്ങളുടെ ബിസിനസ്സ് ആവശ്യങ്ങൾക്ക് അനുയോജ്യമായ പിഡിഎഫ് ഡൗൺലോഡ് ചെയ്യുക.',
      'tax_generate_btn': 'റിപ്പോർട്ട് സൃഷ്ടിച്ച് ഡൗൺലോഡ് ചെയ്യുക',
    },
    'mni': {
      'app_title': 'গিগট্যাক্স (GigTax)',
      'nav_home': 'য়ুম',
      'nav_analytics': 'নৈনবা',
      'nav_receipts': 'রসিদশিং',
      'nav_tax': 'ট্যাক্স',
      'nav_settings': 'সেটিংস',
      'settings_title': 'সেটিংস মফম',
      'settings_account_info': 'একাউন্টের মরোল',
      'settings_member': 'লেংলবা মীহুৎ',
      'settings_system_toggles': 'সিস্টেম অমসুং তোগল',
      'settings_sms_title': 'শেন থুমগী এসএমএস পার্সিং',
      'settings_sms_sub': 'এসএমএস রসিদ খুদিং মখাদা প্রসেস তৌবীনবা',
      'settings_imports_title': 'স্বয়ংক্রিয় স্টেটমেন্ট ইম্পোর্ট',
      'settings_imports_sub': 'CSV অমসুং টেক্সট ফাইলশিং ওনবা য়াহনবা',
      'settings_notif_title': 'পাউদমগী পুৱারী সংহন্নবা',
      'settings_notif_sub': 'অ্যাপ মনুংগী পাউদমশিং মফম অসিদা থম্নবা',
      'settings_biometric_title': 'বায়োমেট্রিক লক স্ক্রিন',
      'settings_biometric_sub': 'অ্যাপ হৌবদা খুৎনা বা ফেসিডী পুথোক্নবা',
      'settings_monetization': 'শেন তানবা অমসুং বিজনেস চাওখৎনবা',
      'settings_upgrade': 'গিগট্যাক্স প্রো-দা আপগ্রেড তৌবীয়ু',
      'settings_upgrade_sub': 'হোয়াট-ইফ সিমুলেটর, এআই ট্যাক্স উপদেষ্টা অমসুং আনলিমিটেড পিডিএফ পিডিএফ ফংবীয়ু',
      'settings_founder': 'লিংখৎলবা কম্যান্ড সেন্টার',
      'settings_founder_sub': 'স্টার্টআপকী হকশেল অমসুং মতেংগী টিকিটশিং',
      'settings_support': 'সহায়তা টিকিট অমসুং মতামত থাবীয়ু',
      'settings_support_sub': 'মটিং য়েংবীয়ু অমসুং ফিডব্যাক পীবীয়ু',
      'settings_referral': 'শেয়ার তৌবা অমসুং মনাশিং',
      'settings_referral_sub': 'রিফরেল কোড শেয়ার তৌবীয়ু অমসুং ₹৫০০ ফংবীয়ু',
      'settings_storage': 'স্টোরেজ অমসুং ম্যানেজমেন্ট',
      'settings_clear_logs': 'লেনদেনের লগ মুৎথৎপা',
      'settings_clear_logs_sub': 'থল্লাবা লেনদেন রেকর্ডশিং মুৎথৎপা',
      'settings_import_mock': 'পরীক্ষামূলক ডেটা ইম্পোর্ট',
      'settings_import_mock_sub': 'পরীক্ষা তৌনবগীদমক রসিদশিং হাপচিনবা',
      'tax_report_center': 'ট্যাক্স রিপোর্ট সেন্টার (CA-Ready)',
      'tax_report_sub': 'নাকলগী পিডিএফশিং ডাউনলোড তৌবীয়ু.',
      'tax_generate_btn': 'রিপোর্ট শেম্বা অমসুং ডাউনলোড তৌবা',
    },
    'mr': {
      'app_title': 'गिगटॅक्स (GigTax)',
      'nav_home': 'मुख्यपृष्ठ',
      'nav_analytics': 'विश्लेषण',
      'nav_receipts': 'पावत्या',
      'nav_tax': 'टॅक्स',
      'nav_settings': 'सेटिंग्ज',
      'settings_title': 'सेटिंग्ज केंद्र',
      'settings_account_info': 'खात्याची माहिती',
      'settings_member': 'सत्यापित सदस्य',
      'settings_system_toggles': 'सिस्टम आणि टॉगल',
      'settings_sms_title': 'स्वयंचलित एसएमएस पार्सिंग',
      'settings_sms_sub': 'पार्श्वभूमीवर वित्तीय पावती एसएमएस प्रक्रिया करा',
      'settings_imports_title': 'स्वयंचलित स्टेटमेंट आयात',
      'settings_imports_sub': 'CSV आणि मजकूर स्टेटमेंट रूपांतरणास परवानगी द्या',
      'settings_notif_title': 'सूचना इतिहास जतन करा',
      'settings_notif_sub': 'अॅपमधील सूचना स्थानिक इतिहासामध्ये जतन करा',
      'settings_biometric_title': 'बायोमेट्रिक लॉक स्क्रीन',
      'settings_biometric_sub': 'अॅप सुरू करताना फिंगरप्रिंट/फेस आयडी विचारा',
      'settings_monetization': 'मुद्रीकरण आणि स्टार्टअप विकास',
      'settings_upgrade': 'गिगटॅक्स प्रो वर अपग्रेड करा',
      'settings_upgrade_sub': 'व्हॉट-इफ सिम्युलेटर, स्थानिक एआय टॅक्स सल्लागार आणि अमर्यादित पीडीएफ मिळवा',
      'settings_founder': 'संस्थापक कमांड सेंटर',
      'settings_founder_sub': 'स्टार्टअप आरोग्य, ग्राहक धारणा आणि समर्थन तिकिटे',
      'settings_support': 'मदत तिकीट आणि अभिप्राय पाठवा',
      'settings_support_sub': 'अनुभवाला रेटिंग द्या, बग अहवाल सबमिट करा',
      'settings_referral': 'रेफरल कार्यक्रम आणि बक्षिसे',
      'settings_referral_sub': 'तुमचा रेफरल कोड शेअर करा आणि ₹५०० प्रो क्रेडिट मिळवा',
      'settings_storage': 'स्टोरेज आणि व्यवस्थापन',
      'settings_clear_logs': 'व्यवहार लॉग साफ करा',
      'settings_clear_logs_sub': 'सर्व स्थानिक आणि कॅश केलेले व्यवहार रेकॉर्ड हटवा',
      'settings_import_mock': 'चाचणी डेटा आयात करा',
      'settings_import_mock_sub': 'चाचणीसाठी ६+ बनावट पावत्या जोडा',
      'tax_report_center': 'टॅक्स रिपोर्ट केंद्र (CA-Ready)',
      'tax_report_sub': 'तुमच्या व्यवसायाच्या गरजेनुसार पीडीएफ डाउनलोड करा.',
      'tax_generate_btn': 'अहवाल तयार करा आणि डाउनलोड करा',
    },
    'ne': {
      'app_title': 'गिगट्याक्स (GigTax)',
      'nav_home': 'गृहपृष्ठ',
      'nav_analytics': 'विश्लेषण',
      'nav_receipts': 'रसिदहरू',
      'nav_tax': 'कर',
      'nav_settings': 'सेटिङहरू',
      'settings_title': 'सेटिङ केन्द्र',
      'settings_account_info': 'खाता जानकारी',
      'settings_member': 'प्रमाणित सदस्य',
      'settings_system_toggles': 'प्रणाली र टगलहरू',
      'settings_sms_title': 'स्वचालित एसएमएस पार्सिङ',
      'settings_sms_sub': 'पृष्ठभूमिमा वित्तीय रसिद एसएमएस प्रक्रिया गर्नुहोस्',
      'settings_imports_title': 'स्वचालित विवरण आयात',
      'settings_imports_sub': 'CSV र पाठ विवरण रूपान्तरण अनुमति दिनुहोस्',
      'settings_notif_title': 'सूचना इतिहास बचत गर्नुहोस्',
      'settings_notif_sub': 'इन-एप सूचनाहरू स्थानीय इतिहासमा बचत गर्नुहोस्',
      'settings_biometric_title': 'बायोमेट्रिक लक स्क्रिन',
      'settings_biometric_sub': 'एप सुरु गर्दा फिंगरप्रिन्ट/फेस आईडी माग्नुहोस्',
      'settings_monetization': 'मुद्रीकरण र स्टार्टअप वृद्धि',
      'settings_upgrade': 'गिगट्याक्स प्रोमा अपग्रेड गर्नुहोस्',
      'settings_upgrade_sub': 'वॉट-इफ सिम्युलेटर, स्थानीय एआई कर सल्लाहकार र असीमित पीडीएफ प्राप्त गर्नुहोस्',
      'settings_founder': 'संस्थापक कमान्ड सेन्टर',
      'settings_founder_sub': 'स्टार्टअप स्वास्थ्य, प्रयोगकर्ता प्रतिधारण र समर्थन टिकटहरू',
      'settings_support': 'मदत टिकट र प्रतिक्रिया पठाउनुहोस्',
      'settings_support_sub': 'अनुभव मूल्याङ्कन गर्नुहोस्, बग रिपोर्ट सबमिट गर्नुहोस्',
      'settings_referral': 'रेफरल कार्यक्रम र पुरस्कारहरू',
      'settings_referral_sub': 'आफ्नो रेफरल कोड साझा गर्नुहोस् र ₹५०० प्रो क्रेडिट कमाउनुहोस्',
      'settings_storage': 'स्टोरेज र व्यवस्थापन',
      'settings_clear_logs': 'लेनदेन लगहरू सफा गर्नुहोस्',
      'settings_clear_logs_sub': 'सबै स्थानीय र क्यास गरिएका लेनदेन रेकर्डहरू हटाउनुहोस्',
      'settings_import_mock': 'परीक्षण डेटा आयात गर्नुहोस्',
      'settings_import_mock_sub': 'परीक्षणका लागि ६+ नक्कली रसिदहरू थप्नुहोस्',
      'tax_report_center': 'कर रिपोर्ट केन्द्र (CA-Ready)',
      'tax_report_sub': 'आफ्नो व्यावसायिक आवश्यकता अनुसार पीडीएफ डाउनलोड गर्नुहोस्।',
      'tax_generate_btn': 'रिपोर्ट बनाउनुहोस् र डाउनलोड गर्नुहोस्',
    },
    'or': {
      'app_title': 'ଗିଗଟ୍ୟାକ୍ସ (GigTax)',
      'nav_home': 'ମୁଖ୍ୟ ପୃଷ୍ଠା',
      'nav_analytics': 'ବିଶ୍ଳେଷଣ',
      'nav_receipts': 'ରସିଦ ସମୂହ',
      'nav_tax': 'ଟ୍ୟାକ୍ସ',
      'nav_settings': 'ସେଟିଙ୍ଗସ',
      'settings_title': 'ସେଟିଙ୍ଗସ କେନ୍ଦ୍ର',
      'settings_account_info': 'ଖାତା ସୂଚନା',
      'settings_member': 'ଯାଞ୍ଚ ହୋଇଥିବା ସଦସ୍ୟ',
      'settings_system_toggles': 'ସିଷ୍ଟମ ଏବଂ ଟଗଲସ',
      'settings_sms_title': 'ସ୍ୱୟଂଚାଳିତ ଏସଏମଏସ ପାର୍ସିଙ୍ଗ',
      'settings_sms_sub': 'ବ୍ୟାକଗ୍ରାଉଣ୍ଡରେ ଆର୍ଥିಕ ରସିଦ ଏସଏମଏସ ପ୍ରୋସେସ କରନ୍ତୁ',
      'settings_imports_title': 'ସ୍ୱୟଂଚาଳିତ ଷ୍ଟେଟମେଣ୍ଟ ଆମଦାନୀ',
      'settings_imports_sub': 'CSV ଏବଂ ଟେକ୍ସଟ ଷ୍ଟେଟମେଣ୍ଟ ରୂପାନ୍ତରକୁ ଅନୁମତି ଦିଅନ୍ତୁ',
      'settings_notif_title': 'ସୂଚନା ଇତିହାସ ସଞ୍ଚୟ କରନ୍ତุ',
      'settings_notif_sub': 'ଇନ-ଆପ ସୂଚନା ଗୁଡିକୁ ସ୍ଥାନୀୟ ଇତିହାସରେ ସଞ୍ଚୟ କରନ୍ତୁ',
      'settings_biometric_title': 'ବାୟୋମେଟ୍ରିକ ଲକ ସ୍କ୍ରିନ',
      'settings_biometric_sub': 'ଆପ ଖୋଲିବା ସମୟରେ ଫିଙ୍ଗରପ୍ରିଣ୍ଟ/ଫେସ ଆଇଡି ମାଗନ୍ତୁ',
      'settings_monetization': 'ମୋନେଟାଇଜେସନ ଏବଂ ଷ୍ଟାର୍ଟଅପ ବିକାଶ',
      'settings_upgrade': 'ଗିଗଟ୍ୟାକ୍ସ ପ୍ରୋକୁ ଅପଗ୍ରେଡ କରନ୍ତୁ',
      'settings_upgrade_sub': 'ୱାଟ-ଇଫ ସିମୁଲେଟର, ସ୍ଥାନୀୟ ଏଆଇ ଟ୍ୟାକ୍ସ ପରାମର୍ଶଦାତା ଏବଂ ଅସୀମିତ ପିଡିଏଫ ପାଆନ୍ତୁ',
      'settings_founder': 'ପ୍ରତିଷ୍ଠାତା କମାଣ୍ଡ ସେଣ୍ଟର',
      'settings_founder_sub': 'ଷ୍ଟାର୍ଟଅପ ସ୍ୱାସ୍ଥ୍ୟ, ଗ୍ରାହକ ଧାରଣ ଏବଂ ସପୋର୍ଟ ଟିକେଟ',
      'settings_support': 'ସପୋର୍ଟ ଟିକେଟ ଏବଂ ପ୍ରତିକ୍ରିୟା ପଠାନ୍ତୁ',
      'settings_support_sub': 'ଅନୁଭବକୁ ରେଟିଂ ଦିଅନ୍ତୁ, ବଗ ରିପୋର୍ଟ ଦାଖଲ କରନ୍ତୁ',
      'settings_referral': 'ରେଫରାଲ କାର୍ଯ୍ୟକ୍ରମ ଏବଂ ପୁରସ୍କାର',
      'settings_referral_sub': 'ଆପଣଙ୍କ ରେଫରାଲ କୋଡ ସେୟାର କରନ୍ତୁ ଏବଂ ₹୫୦୦ ପ୍ରୋ କ୍ରେଡିଟ ପାଆନ୍ତୁ',
      'settings_storage': 'ଷ୍ଟୋରେଜ ଏବଂ ପରିଚାଳନା',
      'settings_clear_logs': 'କାରବାର ଲଗ ସଫା କରନ୍ତୁ',
      'settings_clear_logs_sub': 'ସମସ୍ତ ସ୍ଥାନୀୟ ଏବଂ କ୍ୟାଶେଡ କାରବାର ରେକର୍ଡ ହଟାନ୍ତୁ',
      'settings_import_mock': 'ପରୀକ୍ଷଣ ଡାଟା ଆମଦାନୀ କରନ୍ତୁ',
      'settings_import_mock_sub': 'ପରୀକ୍ଷଣ ପାଇଁ ୬+ ନକଲି ରସିଦ ଯୋଡନ୍ତୁ',
      'tax_report_center': 'ଟ୍ୟାକ୍ସ ରିପୋର୍ଟ କେନ୍ଦ୍ର (CA-Ready)',
      'tax_report_sub': 'ଆପଣଙ୍କ ବ୍ୟବସାୟର ଆବଶ୍ୟକତା ଅନୁଯାୟୀ ପିଡିଏଫ ଡାଉନଲୋଡ କରନ୍ତୁ।',
      'tax_generate_btn': 'ରିପୋର୍ଟ ପ୍ରସ୍ତୁତ କରନ୍ତୁ ଏବଂ ଡାଉନଲୋଡ କରନ୍ତୁ',
    },
    'pa': {
      'app_title': 'ਗਿਗਟੈਕਸ (GigTax)',
      'nav_home': 'ਮੁੱਖ ਪੰਨਾ',
      'nav_analytics': 'ਵਿਸ਼ਲੇਸ਼ਣ',
      'nav_receipts': 'ਰਸੀਦਾਂ',
      'nav_tax': 'ਟੈਕਸ',
      'nav_settings': 'ਸੈਟਿੰਗਜ਼',
      'settings_title': 'ਸੈਟਿੰਗਜ਼ ਕੇਂਦਰ',
      'settings_account_info': 'ਖਾਤਾ ਜਾਣਕਾਰੀ',
      'settings_member': 'ਪ੍ਰਮਾਣਿਤ ਮੈਂਬਰ',
      'settings_system_toggles': 'ਸਿਸਟਮ ਅਤੇ ਟੌਗਲ',
      'settings_sms_title': 'ਸਵੈਚਾਲਿਤ ਐਸਐਮਐਸ ਪਾਰਸਿੰਗ',
      'settings_sms_sub': 'ਬੈਕਗ੍ਰਾਉਂਡ ਵਿੱਚ ਵਿੱਤੀ ਰਸੀਦ ਐਸਐਮਐਸ ਪ੍ਰੋਸੈਸ ਕਰੋ',
      'settings_imports_title': 'ਸਵੈਚਾਲਿਤ ਸਟੇਟਮੈਂਟ ਇੰਪੋਰਟ',
      'settings_imports_sub': 'CSV ਅਤੇ ਟੈਕਸਟ ਸਟੇਟਮੈਂਟ ਪਰਿਵਰਤਨ ਦੀ ਆਗਿਆ ਦਿਓ',
      'settings_notif_title': 'ਸੂਚਨਾ ਇਤਿਹਾਸ ਸੁਰੱਖਿਅਤ ਕਰੋ',
      'settings_notif_sub': 'ਇਨ-ਐਪ ਸੂਚਨਾਵਾਂ ਨੂੰ ਸਥਾਨਕ ਇਤਿਹਾਸ ਵਿੱਚ ਸੁਰੱਖਿਅਤ ਕਰੋ',
      'settings_biometric_title': 'ਬਾਇਓਮੀਟ੍ਰਿਕ ਲਾਕ ਸਕ੍ਰੀਨ',
      'settings_biometric_sub': "ਐਪ ਸ਼ੁਰੂ ਹੋਣ 'ਤੇ ਫਿੰਗਰਪ੍ਰਿੰਟ/ਫੇਸ ਆਈਡੀ ਮੰਗੋ",
      'settings_monetization': 'ਮੋਨੇਟਾਈਜ਼ੇਸ਼ਨ ਅਤੇ ਸਟਾਰਟਅੱਪ ਵਿਕਾਸ',
      'settings_upgrade': 'ਗਿਗਟੈਕਸ ਪ੍ਰੋ ਵਿੱਚ ਅਪਗ੍ਰੇਡ ਕਰੋ',
      'settings_upgrade_sub': 'ਵੌਟ-ਇਫ਼ ਸਿਮੂਲੇਟਰ, ਸਥਾਨਕ ਏਆਈ ਟੈਕਸ ਸਲਾਹਕਾਰ ਅਤੇ ਅਸੀਮਤ ਪੀਡੀਐਫ ਪ੍ਰਾਪਤ ਕਰੋ',
      'settings_founder': 'ਸੰਸਥਾਪਕ ਕਮਾਂਡ ਸੈਂਟਰ',
      'settings_founder_sub': 'ਸਟਾਰਟਅੱਪ ਸਿਹਤ, ਉਪਭੋਗਤਾ ਰਿਟੈਂਸ਼ਨ ਅਤੇ ਸਹਾਇਤਾ ਟਿਕਟਾਂ',
      'settings_support': 'ਸਹਾਇਤਾ ਟਿਕਟ ਅਤੇ ਫੀਡਬੈਕ ਭੇਜੋ',
      'settings_support_sub': 'ਅਨੁਭਵ ਨੂੰ ਰੇਟ ਕਰੋ, ਬਗ ਰਿਪੋਰਟ ਜਮ੍ਹਾਂ ਕਰੋ',
      'settings_referral': 'ਰੈਫਰਲ ਪ੍ਰੋਗਰਾਮ ਅਤੇ ਇਨਾਮ',
      'settings_referral_sub': 'ਆਪਣਾ ਰੈਫਰਲ ਕੋਡ ਸਾਂਝਾ ਕਰੋ ਅਤੇ ₹੫੦੦ ਪ੍ਰੋ ਕ੍ਰੈਡਿਟ ਕਮਾਓ',
      'settings_storage': 'ਸਟੋਰੇਜ ਅਤੇ ਪ੍ਰਬੰਧਨ',
      'settings_clear_logs': 'ਟ੍ਰਾਂਜੈਕਸ਼ਨ ਲੌਗ ਸਾਫ਼ ਕਰੋ',
      'settings_clear_logs_sub': 'ਸਾਰੇ ਸਥਾਨਕ ਅਤੇ ਕੈਸ਼ ਕੀਤੇ ਟ੍ਰਾਂਜੈਕਸ਼ਨ ਰਿਕਾਰਡ ਹਟਾਓ',
      'settings_import_mock': 'ਟੈਸਟ ਡੇਟਾ ਇੰਪੋਰਟ ਕਰੋ',
      'settings_import_mock_sub': 'ਟੈਸਟਿੰਗ ਲਈ ੬+ ਨਕਲੀ ਰਸੀਦਾਂ ਸ਼ਾਮਲ ਕਰੋ',
      'tax_report_center': 'ਟੈਕਸ ਰਿਪੋਰਟ ਕੇਂਦਰ (CA-Ready)',
      'tax_report_sub': 'ਆਪਣੀ ਕਾਰੋਬਾਰੀ ਜ਼ਰੂਰਤਾਂ ਦੇ ਅਨੁਸਾਰ ਪੀਡੀਐਫ ਡਾਊਨਲੋਡ ਕਰੋ।',
      'tax_generate_btn': 'ਰਿਪੋਰਟ ਤਿਆਰ ਕਰੋ ਅਤੇ ਡਾਊਨਲੋਡ ਕਰੋ',
    },
    'sa': {
      'app_title': 'गिगटैक्स (GigTax)',
      'nav_home': 'मुख्यपृष्ठम्',
      'nav_analytics': 'विश्लेषणम्',
      'nav_receipts': 'प्राप्तयः',
      'nav_tax': 'करः',
      'nav_settings': 'सेटिंग्स',
      'settings_title': 'सेटिंग्स केन्द्रम्',
      'settings_account_info': 'लेखा विवरणम्',
      'settings_member': 'सत्यापितः सदस्यः',
      'settings_system_toggles': 'तन्त्रं टॉगल च',
      'settings_sms_title': 'स्वचालितं एसएमएस विश्लेषणम्',
      'settings_sms_sub': 'पृष्ठभूमौ वित्तीय संदेशाः संसाधयन्तु',
      'settings_imports_title': 'स्वचालितं विवरण आयातम्',
      'settings_imports_sub': 'CSV पाठ्यविवरणस्य च परिवर्तनम् अनुमन्यताम्',
      'settings_notif_title': 'सूचना इतिहासः सुरक्षितः क्रियताम्',
      'settings_notif_sub': 'अनुप्रयोगस्य सूचनाः स्थानीय इतिहासे रक्षन्तु',
      'settings_biometric_title': 'बायोमेट्रिक लॉक स्क्रीन',
      'settings_biometric_sub': 'प्रारम्भे अंगुलिमुद्रा/फेस आईडी याच्यताम्',
      'settings_monetization': 'मुद्रीकरणं स्टार्टअप विकासः च',
      'settings_upgrade': 'गिगटैक्स प्रो मध्ये अपग्रेड क्रियताम्',
      'settings_upgrade_sub': 'व्हॉट-इफ सिम्युलेटर, स्थानिक एआई करसल्लाहकारः, असीमित पीडीएफ च लभ्यताम्',
      'settings_founder': 'संस्थापक कमाण्ड सेन्टर',
      'settings_founder_sub': 'स्टार्टअप स्वास्थ्यम्, प्रयोक्ता प्रतिधारणं, सहायता पत्राणि च',
      'settings_support': 'सहायता पत्रं प्रतिक्रिया च प्रेष्यताम्',
      'settings_support_sub': 'अनुभवस्य मूल्यांकनं कुर्वन्तु, दोषनिवेदनं प्रेषयन्तु',
      'settings_referral': 'रेफरल कार्यक्रमः पुरस्कारः च',
      'settings_referral_sub': 'स्वकीय रेफरल कोड प्रेष्य ₹५०० प्रो क्रेडिट लभ्यताम्',
      'settings_storage': 'सञ्चयः प्रबन्धनं च',
      'settings_clear_logs': 'व्यवहार इतिहासः शोधनीयः',
      'settings_clear_logs_sub': 'सर्वे स्थानीय व्यवहार अभिलेखाः विलोप्यन्ताम्',
      'settings_import_mock': 'परीक्षण विवरण आयातम्',
      'settings_import_mock_sub': 'परीक्षणार्थं ६+ कृत्रिम प्राप्तयः योज्यन्ताम्',
      'tax_report_center': 'कर विवरण केन्द्रम् (CA-Ready)',
      'tax_report_sub': 'व्यापार आवश्यकतानुसारं पीडीएफ विवरणाणि लभ्यताम्।',
      'tax_generate_btn': 'विवरणं सृष्ट्वा डाउनलोड क्रियताम्',
    },
    'sat': {
      'app_title': 'ᱜᱤᱜᱽᱴᱮᱠᱥ (GigTax)',
      'nav_home': 'ᱚᱲᱟᱜ',
      'nav_analytics': 'ᱵᱤᱥᱞᱮᱥᱚᱱ',
      'nav_receipts': 'ᱨᱩᱥᱤᱫᱽ ᱠᱚ',
      'nav_tax': 'ᱴᱮᱠᱥ',
      'nav_settings': 'ᱥᱮᱴᱤᱝᱥ ᱠᱚ',
      'settings_title': 'ᱥᱮᱴᱤᱝᱥ ᱛᱟᱞᱢᱟ',
      'settings_account_info': 'ᱮᱠᱟᱶնᱴ ᱵᱟᱰᱟᱭ',
      'settings_member': 'ᱥᱟᱹᱨᱤ ᱟᱠᱟᱱ ᱥᱚᱦᱮᱫ',
      'settings_system_toggles': 'ᱥᱤᱥᱴᱮਮ ᱟᱨ ᱴᱚᱜᱚᱞ ᱠᱚ',
      'settings_sms_title': 'ᱟᱯᱱᱟᱨ ᱛေ ᱮᱥ.ᱮਮ.ᱮᱥ. ᱯᱟᱨᱥᱤᱝ',
      'settings_sms_sub': 'ᱵᱮᱠਗᱨᱟᱶնᱰ ᱨᱮ ᱠﺎᱹਵᱰᱤ ᱨᱩᱥᱤᱫᱽ ᱮᱥ.ᱮਮ.ᱮᱥ. ᱯᱨᱚᱥᱮᱥ ᱢᱮ',
      'settings_imports_title': 'ᱟᱯᱱᱟᱨ ᱛေ ᱥᱴੇޓᱢᱮն্ট ᱟᱹᱜᱩ',
      'settings_imports_sub': 'CSV ᱟᱨ ᱚᱞ ᱥᱴੇޓᱢᱮն্ট ᱵᱚదᱚᱞ ᱮμ ᱢᱮ',
      'settings_notif_title': 'ᱞᱟᱹᱭ ᱱᱟᱜᱟᱢ ᱥᱟᱸᱵᱷᱟᱣ ᱢᱮ',
      'settings_notif_sub': 'ᱮᱯ ᱨᱮᱱᱟᱜ ᱞᱟᱹᱭ ᱠᱚ ᱴᱷᱟᱶ ᱨᱮ ᱥᱟᱸᱵᱷᱟᱣ ᱢᱮ',
      'settings_biometric_title': 'ᱵᱟᱭᱳᱢᱮᱴᱨᱤᱠ ᱞᱚᱠ ᱥᱠᱨᱤᱱ',
      'settings_biometric_sub': 'ᱮᱯ ᱮᱦᱚᱵ ᱨᱮ ᱛᱤ-ਚᱤᱱᱦᱟᱹ/ᱢᱮᱫ-ਚᱤᱱᱦᱟᱹ ᱠᱚᱭ ᱢᱮ',
      'settings_monetization': 'ᱠᱟᱹᱣᱰᱤ ᱟᱨᱡᱟᱣ ᱟᱨ ᱮᱦᱚᱵ ᱦᱟᱨᱟ',
      'settings_upgrade': 'ᱜᱤᱜᱽᱴᱮᱠᱥ ᱯᱨᱳ ᱛᱮ ᱩᱛᱱᱟᱹᱣ ᱢᱮ',
      'settings_upgrade_sub': 'ᱣᱟᱴ-इफ ᱥᱤᱢᱩᱞᱮᱴᱚᱨ, ᱴᱷᱟᱶ ᱮ.ᱟᱭ. ᱴᱮᱠᱥ དᱤସᱟᱹ-ᱮμᱤᱡ ᱟᱨ ᱵᱮᱼᱞᱤᱢᱤᱴ ᱯᱤ.ᱰᱤ.ᱮᱯᱷ. ᱧᱟᱢ ᱢᱮ',
      'settings_founder': 'ᱵᱩᱱᱤᱭᱟᱹᱫᱤ ᱠᱚᱢᱟᱱᱰ ᱛᱟᱞᱢᱟ',
      'settings_founder_sub': 'ᱮᱦᱚᱵ ᱦᱚᱲਮᱚ-ᱥᱟᱶᱟᱨ, ᱵᱮᱵᱷᱟᱨᱤᱭᱟᱹ ᱥᱟᱸᱵᱷᱟᱣ ᱟᱨ ᱜᱚᱲᱚ ᱴᱤᱠᱮᱴ ᱠᱚ',
      'settings_support': 'ᱜᱚᱲᱚ ᱴᱤᱠᱮᱴ ᱟᱨ ᱢᱚᱱᱮ ᱚᱞ ᱵᱷေᱡᱟᱭ ᱢᱮ',
      'settings_support_sub': 'ᱵᱮᱵᱷᱟᱨ ᱨᱮᱱาᱜ ᱢᱟᱹᱱ ᱮᱢ ᱢᱮ, ᱵᱟᱹᱲᱤᱡ ᱨਿਪᱳᱨտ ᱮᱢ ᱢᱮ',
      'settings_referral': 'ᱨᱮᱯᱷᱚᱨᱟᱞ ᱠᱟᱹਮᱤਹᱚᱨᱟ ᱟᱨ ᱥᱤᱨᱯᱷᱟᱹ ᱠᱚ',
      'settings_referral_sub': 'ᱟᱢᱟᱜ ᱨᱮᱯᱷᱚᱨᱟᱞ ᱠᱳᱰ ᱦᱟᱹᱴᱤᱧ ᱢᱮ ᱟᱨ ₹᱕०० ᱠᱨᱮᱰᱤଟ ᱟᱨᱡᱟᱣ ᱢᱮ',
      'settings_storage': 'ᱥᱟᱸᱵᱷᱟᱣ ᱟᱨ ᱪᱟച്ചᱞᱟᱣ',
      'settings_clear_logs': 'ᱠᱟᱹਮᱤ ᱚᱞ ᱥᱟପᱷᱟ ᱢᱮ',
      'settings_clear_logs_sub': 'ᱡᱚᱛੋ ᱴᱷᱟᱶ ᱟᱨ ᱠᱮᱪ ᱟᱠᱟᱱ ᱠᱟᱹਮᱤ ᱨᱮᱠᱳᱰ ᱠᱚ ᱢᱮᱴﺎᱣ ᱢᱮ',
      'settings_import_mock': 'ᱵᱤᱰᱟᱹᱣ ᱰᱮޓᱟ ᱟᱹᱜᱩ ᱢᱮ',
      'settings_import_mock_sub': 'ᱵᱤᱰᱟᱹᱣ ᱞᱟᱹᱜᱤਦ ᱖+ ᱮᱲေ ᱨᱩᱥᱤᱫᱽ ᱥᱮᱞᱮᱫ ᱢᱮ',
      'tax_report_center': 'ᱴᱮᱠᱥ ᱨᱤପᱳᱨտ ᱛᱟᱞᱢᱟ (CA-Ready)',
      'tax_report_sub': 'ᱟᱢᱟᱜ ᱵᱮᱯᱟᱨ ᱞᱟᱹᱠﺘᱤ ᱞᱮᱠᱟᱛେ ᱯᱤ.ᱰᱤ.ᱮᱯᱷ. ᱰᱟᱶնᱞᱳᱰ ᱢᱮ।',
      'tax_generate_btn': 'ᱨᱤପᱳᱨտ ᱵᱮᱱᱟᱣ ᱟᱨ ᱰᱟᱶնᱞᱳᱰ ᱢᱮ',
    },
    'sd': {
      'app_title': 'गिगटैक्स (GigTax)',
      'nav_home': 'घर',
      'nav_analytics': 'तजवीज़',
      'nav_receipts': 'रसीदूं',
      'nav_tax': 'टैक्स',
      'nav_settings': 'सेटिंग्स',
      'settings_title': 'सेटिंग्स मरकज़',
      'settings_account_info': 'खाते जी मालूमात',
      'settings_member': 'सत्यापित मेंबर',
      'settings_system_toggles': 'सिस्टम ऐं टॉगल',
      'settings_sms_title': 'स्वचालित एसएमएस पार्सिंग',
      'settings_sms_sub': 'backगौंड में माली रसीद एसएमएस प्रोग्रेस कर्यो',
      'settings_imports_title': 'स्वचालित स्टेटमेंट इनपुट',
      'settings_imports_sub': 'CSV ऐं टेक्स्ट स्टेटमेंट के कन्वर्ट करण जी इजाज़त डियो',
      'settings_notif_title': 'नोटिफिकेशन हिस्ट्री सँभाळियो',
      'settings_notif_sub': 'इन-ऐप नोटिफिकेशन के लोकल स्टोरेज में रखियो',
      'settings_biometric_title': 'बायोमेट्रिक लॉक स्क्रीन',
      'settings_biometric_sub': 'ऐप शुरू थियण ते उँगरी जो निशान/फेस आईडी पुछो',
      'settings_monetization': 'मुद्रीकरण ऐं स्टार्टअप विकास',
      'settings_upgrade': 'गिगटैक्स प्रो में अपग्रेड कर्यो',
      'settings_upgrade_sub': 'वॉट-इफ सिम्युलेटर, लोकल एआई टैक्स सलाहकार ऐं अनलिमिटेड पीडीएफ पायो',
      'settings_founder': 'बानी कमांड सेंटर',
      'settings_founder_sub': 'स्टार्टअप सेहत, उपभोक्ता प्रतिधारण ऐं मदद टिकट',
      'settings_support': 'मदद टिकट ऐं फीडबैक मोकळियो',
      'settings_support_sub': 'अनुभव के रेट कर्यो, बग रिपोर्ट सबमिट कर्यो',
      'settings_referral': 'रेफरल प्रोग्राम ऐं इनाम',
      'settings_referral_sub': 'पंहिंजो रेफरल कोड शेयर कर्यो ऐं ₹५०० प्रो क्रेडिट कमायो',
      'settings_storage': 'स्टोरेज ऐं प्रबंधन',
      'settings_clear_logs': 'लेनदेन लॉग साफ कर्यो',
      'settings_clear_logs_sub': 'सभ लोकल ऐं कैश्ड लेनदेन रिकॉर्ड हटाए छड्यो',
      'settings_import_mock': 'टेस्ट डेटा इंपोर्ट कर्यो',
      'settings_import_mock_sub': 'डैशबोर्ड टेस्टिंग लए ६+ मॉक रसीदूं जोड्यो',
      'tax_report_center': 'टैक्स रिपोर्ट सेंटर (CA-Ready)',
      'tax_report_sub': 'पंहिंजो कम जी जरूरत मुताविक पीडीएफ डाउनलोड कर्यो।',
      'tax_generate_btn': 'रिपोर्ट ठाहायो ऐं डाउनलोड कर्यो',
    },
    'ta': {
      'app_title': 'கிக்டாக்ஸ் (GigTax)',
      'nav_home': 'முகப்பு',
      'nav_analytics': 'பகுப்பாய்வு',
      'nav_receipts': 'ரசீதுகள்',
      'nav_tax': 'வரி',
      'nav_settings': 'அமைப்புகள்',
      'settings_title': 'அமைப்புகள் மையம்',
      'settings_account_info': 'கணக்கு தகவல்',
      'settings_member': 'சரிபார்க்கப்பட்ட உறுப்பினர்',
      'settings_system_toggles': 'கணினி மற்றும் மாற்று சுவிட்சுகள்',
      'settings_sms_title': 'தானியங்கி எஸ்எம்எஸ் பகுப்பாய்வு',
      'settings_sms_sub': 'பின்னணியில் நிதி ரசீது எஸ்எம்எஸ்ஸை செயலாக்குங்கள்',
      'settings_imports_title': 'தானியங்கி அறிக்கை இறக்குமதி',
      'settings_imports_sub': 'CSV மற்றும் உரை அறிக்கைகளின் மாற்றங்களை அனுமதியுங்கள்',
      'settings_notif_title': 'அறிவிப்பு வரலாற்றைச் சேமி',
      'settings_notif_sub': 'பயன்பாட்டு அறிவிப்புகளை உள்ளூர் வரலாற்றில் சேமிக்கவும்',
      'settings_biometric_title': 'கைரேகை பூட்டுத் திரை',
      'settings_biometric_sub': 'பயன்பாடு தொடங்கும் போது கைரேகை/முக அடையாளத்தைக் கேளுங்கள்',
      'settings_monetization': 'பணமாக்குதல் மற்றும் தொடக்க வளர்ச்சி',
      'settings_upgrade': 'கிக்டாக்ஸ் ப்ரோவுக்கு மேம்படுத்தவும்',
      'settings_upgrade_sub': 'வாட்-இஃப் சிமுலேட்டர், உள்ளூர் ஏஐ வரி ஆலோசகர் மற்றும் வரம்பற்ற பிடிஎஃப் பெறுக',
      'settings_founder': 'நிறுவனர் கட்டளை மையம்',
      'settings_founder_sub': 'தொடக்க ஆரோக்கியம், பயனர் தக்கவைப்பு மற்றும் ஆதரவு டிக்கெட்டுகள்',
      'settings_support': 'ஆதரவு டிக்கெட் மற்றும் கருத்துக்களைச் சமர்ப்பிக்கவும்',
      'settings_support_sub': 'அனுபவத்தை மதிப்பிடுங்கள், பிழை அறிக்கைகளை சமர்ப்பிக்கவும்',
      'settings_referral': 'பரிந்துரை திட்டம் மற்றும் வெகுமதிகள்',
      'settings_referral_sub': 'உங்கள் பரிந்துரை குறியீட்டைப் பகிர்ந்து ₹500 ப்ரோ கிரெடிட்டைப் பெறுங்கள்',
      'settings_storage': 'சேமிப்பு மற்றும் மேலாண்மை',
      'settings_clear_logs': 'பரிவர்த்தனை பதிவுகளை அழிக்கவும்',
      'settings_clear_logs_sub': 'அனைத்து உள்ளூர் மற்றும் தற்காலிக சேமிப்பு பரிவர்த்தனை பதிவுகளை அழிக்கவும்',
      'settings_import_mock': 'சோதனை தரவை இறக்குமதி செய்',
      'settings_import_mock_sub': 'சோதனைக்காக 6+ போலி ரசீதுகளைச் சேர்க்கவும்',
      'tax_report_center': 'வரி அறிக்கை மையம் (CA-Ready)',
      'tax_report_sub': 'உங்கள் வணிகத் தேவைகளுக்கு ஏற்ற பிடிஎஃப் அறிக்கையைப் பதிவிறக்கவும்.',
      'tax_generate_btn': 'அறிக்கையை உருவாக்கி பதிவிறக்கவும்',
    },
    'te': {
      'app_title': 'గిగ్‌టాక్స్ (GigTax)',
      'nav_home': 'హోమ్',
      'nav_analytics': 'విశ్లేషణ',
      'nav_receipts': 'రసీదులు',
      'nav_tax': 'పన్ను',
      'nav_settings': 'సెట్టింగ్స్',
      'settings_title': 'సెట్టింగ్స్ కేంద్రం',
      'settings_account_info': 'ఖాతా సమాచారం',
      'settings_member': 'ధృవీకరించబడిన సభ్యుడు',
      'settings_system_toggles': 'సిస్టమ్ మరియు టోగుల్స్',
      'settings_sms_title': 'స్వయంచాలక ఎస్ఎంఎస్ పార్సింగ్',
      'settings_sms_sub': 'నేపథ్యంలో ఆర్థిక రసీదు ఎస్ఎంఎస్‌లను ప్రాసెస్ చేయండి',
      'settings_imports_title': 'స్వయంచాలక నివేదిక దిగుమతులు',
      'settings_imports_sub': 'CSV మరియు టెక్స్ట్ స్టేట్‌మెంట్ మార్పిడులను అనుమతించండి',
      'settings_notif_title': 'అధినోటిఫికేషన్ చరిత్రను సేవ్ చేయండి',
      'settings_notif_sub': 'యాప్ నోటిఫికేషన్‌లను స్థానిక చరిత్రలో సేవ్ చేయండి',
      'settings_biometric_title': 'బయోమెట్రిక్ లాక్ స్క్రీన్',
      'settings_biometric_sub': 'యాప్ ప్రారంభంలో వేలిముద్ర/ఫేస్ ఐడి కోసం అడగండి',
      'settings_monetization': 'మోనటైజేషన్ మరియు స్టార్టప్ వృద్ధి',
      'settings_upgrade': 'గిగ్‌టాక్స్ ప్రోకి అప్‌గ్రేడ్ చేయండి',
      'settings_upgrade_sub': 'వాట్-ఇఫ్ సిమ్యులేటర్, స్థానిక ఎఐ పన్ను సలహాదారు మరియు అపరిమిత పిడిఎఫ్ పొందండి',
      'settings_founder': 'వ్యవస్థాపక కమాండ్ సెంటర్',
      'settings_founder_sub': 'స్టార్టప్ ఆరోగ్యం, వినియోగదారు నిలుపుదల మరియు సపోర్ట్ టిక్కెట్లు',
      'settings_support': 'సపోర్ٹ టికెట్ మరియు అభిప్రాయాన్ని సమర్పించండి',
      'settings_support_sub': 'అనుభవాన్ని రేట్ చేయండి, బగ్ నివేదికలను సమర్పించండి',
      'settings_referral': 'రెఫరల్ ప్రోగ్రామ్ మరియు రివార్డులు',
      'settings_referral_sub': 'మీ రెఫరల్ కోడ్‌ను షేర్ చేయండి మరియు ₹500 ప్రో క్రెడిట్ పొందండి',
      'settings_storage': 'స్టోరేజ్ మరియు మేనేజ్‌మెంట్',
      'settings_clear_logs': 'లావాదేవీల లాగ్‌లను క్లియర్ చేయండి',
      'settings_clear_logs_sub': 'అన్ని స్థానిక మరియు క్యాష్ చేయబడిన లావాదేవీల రికార్డులను తొలగించండి',
      'settings_import_mock': 'టెస్ట్ డేటాను దిగుమతి చేయండి',
      'settings_import_mock_sub': 'టెస్టింగ్ కోసం 6+ నకిలీ రసీదులను జోడించండి',
      'tax_report_center': 'పన్ను నివేదిక కేంద్రం (CA-Ready)',
      'tax_report_sub': 'మీ వ్యాపార అవసరాలకు అనుగుణంగా పిడిఎఫ్ డౌన్‌లోడ్ చేసుకోండి.',
      'tax_generate_btn': 'నివేదికను రూపొందించి డౌన్‌లోడ్ చేయండి',
    },
    'ur': {
      'app_title': 'گگ ٹیکس (GigTax)',
      'nav_home': 'ہوم',
      'nav_analytics': 'تجزیہ',
      'nav_receipts': 'رسیدیں',
      'nav_tax': 'ٹیکس',
      'nav_settings': 'ترتیبات',
      'settings_title': 'ترتیبات مرکز',
      'settings_account_info': 'اکاؤنٹ کی معلومات',
      'settings_member': 'تصدیق شدہ ممبر',
      'settings_system_toggles': 'سسٹم اور ٹوگلز',
      'settings_sms_title': 'خودکار ایس ایم ایس پارسنگ',
      'settings_sms_sub': 'بیک گراؤنڈ میں مالیاتی رسید کے ایس ایم ایس پروسیس کریں',
      'settings_imports_title': 'خودکار اسٹیٹمنٹ امپورٹ',
      'settings_imports_sub': 'CSV اور ٹیکسٹ اسٹیٹمنٹ کنورژن کی اجازت دیں',
      'settings_notif_title': 'نوٹیفکیشن ہسٹری محفوظ کریں',
      'settings_notif_sub': 'ان ایپ نوٹیفکیشنز کو مقامی ہسٹری میں محفوظ کریں',
      'settings_biometric_title': 'بایومیٹرک لاک اسکرین',
      'settings_biometric_sub': 'ایپ اسٹارٹ اپ پر فنگر پرنٹ/فیس آئی ڈی مانگیں',
      'settings_monetization': 'مونیٹائزیشن اور اسٹارٹ اپ ترقی',
      'settings_upgrade': 'گگ ٹیکس پرو میں اپ گریڈ کریں',
      'settings_upgrade_sub': 'واٹ-اف سمیلیٹر، مقامی اے آئی ٹیکس ایڈوائزر اور لامحدود پی ڈی ایف حاصل کریں',
      'settings_founder': 'بانی کمانڈ سینٹر',
      'settings_founder_sub': 'اسٹارٹ اپ صحت، صارفین کو برقرار رکھنے اور سپورٹ ٹکٹ',
      'settings_support': 'سپورٹ ٹکٹ اور رائے بھیجیں',
      'settings_support_sub': 'اپنے تجربے کی درجہ بندی کریں، بگ رپورٹ جمع کروائیں',
      'settings_referral': 'ریفرل پروگرام اور انعامات',
      'settings_referral_sub': 'اپنا ریفرل کوڈ شیئر کریں اور ₹500 پرو کریڈٹ حاصل کریں',
      'settings_storage': 'اسٹوریج اور اسٹور کرنے کا نظام',
      'settings_clear_logs': 'ٹرانزیکشن لاگز صاف کریں',
      'settings_clear_logs_sub': 'تمام مقامی اور کیشڈ ٹرانزیکشن ریکارڈز صاف کریں',
      'settings_import_mock': 'ٹیسٹ ڈیٹا امپورٹ کریں',
      'settings_import_mock_sub': 'ٹیسٹنگ کے لیے 6+ فرضی رسیدیں شامل کریں',
      'tax_report_center': 'ٹیکس رپورٹ مرکز (CA-Ready)',
      'tax_report_sub': 'اپنے کاروبار کی ضروریات کے مطابق پی ڈی ایف ڈاؤن لوڈ کریں۔',
      'tax_generate_btn': 'رپورٹ تیار اور ڈاؤن لوڈ کریں',
    }
  };

  String translate(String key) {
    return _localizedValues[_currentLocale]?[key] ?? key;
  }
}
